import type { Post, Author, Comment } from './community-types';

// ── Sample Authors ─────────────────────────────────────
const authors: Record<string, Author> = {
  party: { id: 'u1', nickname: '파티러버', level: '파티피플', xp: 1200 },
  weekend: { id: 'u2', nickname: '위켄드홀릭', level: '클러버', xp: 350 },
  newbie: { id: 'u3', nickname: '뉴비탈출', level: '클러버', xp: 200 },
  busan: { id: 'u4', nickname: '부산사람', level: '뉴비', xp: 80 },
  solo: { id: 'u5', nickname: '솔로댄서', level: 'VIP', xp: 2500 },
  hongdae: { id: 'u6', nickname: '홍대매니아', level: '파티피플', xp: 800 },
  music: { id: 'u7', nickname: '뮤직러버', level: '클러버', xp: 400 },
  lounge: { id: 'u8', nickname: '라운지탐험가', level: '파티피플', xp: 900 },
  clubmaster: { id: 'u9', nickname: '클럽마스터', level: '레전드', xp: 5200 },
  vip: { id: 'u10', nickname: 'VIP단골', level: 'VIP', xp: 3100 },
  dance: { id: 'u11', nickname: '댄스킹', level: 'VIP', xp: 2800 },
  tour: { id: 'u12', nickname: '전국투어', level: '레전드', xp: 6000 },
  safe: { id: 'u13', nickname: '안전귀가', level: '파티피플', xp: 700 },
  fashion: { id: 'u14', nickname: '패션에디터', level: 'VIP', xp: 3500 },
  style: { id: 'u15', nickname: '스타일리스트K', level: '파티피플', xp: 1500 },
};

function makeComment(id: string, postId: string, authorKey: string, content: string, replies?: Comment[]): Comment {
  return {
    id,
    postId,
    author: authors[authorKey] || authors.newbie,
    content,
    createdAt: '2026-03-13T12:00:00Z',
    likes: Math.floor(Math.random() * 30),
    isLiked: false,
    replies,
  };
}

// ── Free Board Posts ───────────────────────────────────
export const freePosts: Post[] = [
  {
    id: 'f1', board: 'free', title: '오늘 강남 클럽 분위기 어떤가요?',
    content: '주말인데 강남 클럽 분위기 어떤지 궁금합니다. 강남클럽 레이스나 압구정클럽 하입 가보신 분 계신가요? 오늘 처음 갈 건데 혼자라서 좀 걱정되네요. 보통 몇 시쯤 가는 게 좋을까요? 드레스코드도 궁금합니다.',
    excerpt: '주말인데 강남 클럽 분위기 어떤지 궁금합니다...',
    author: authors.party, createdAt: '2026-03-13T20:30:00Z',
    views: 342, likes: 28, isLiked: false, isBookmarked: false,
    commentCount: 15, images: [], hashtags: ['강남', '클럽', '주말'],
    readTimeMin: 1, isPopular: false, isReported: false,
    comments: [
      makeComment('c1', 'f1', 'clubmaster', '강남클럽 레이스는 12시 넘어서 가야 분위기 제대로 나요. 드레스코드는 스마트 캐주얼이면 충분!', [
        makeComment('c1-1', 'f1', 'party', '감사합니다! 그럼 11시 반쯤 출발하면 되겠네요'),
        makeComment('c1-2', 'f1', 'newbie', '저도 궁금했는데 도움 됐어요'),
      ]),
      makeComment('c2', 'f1', 'weekend', '압구정클럽 하입도 괜찮아요. 힙합 좋아하시면 압구정클럽 하입 추천'),
    ],
  },
  {
    id: 'f2', board: 'free', title: '주말마다 클럽 가는 사람 저만 그런가요 ㅋㅋ',
    content: '요즘 금토 빠지지 않고 클럽을 가는데, 주변에 같이 갈 사람이 점점 없어지네요. 다들 바쁘다고 하는데 저만 이러는 건가... 혹시 비슷한 분 계신가요? 클럽 동호회 같은 거 있으면 좋겠는데.',
    excerpt: '요즘 금토 빠지지 않고 클럽을 가는데...',
    author: authors.weekend, createdAt: '2026-03-13T18:00:00Z',
    views: 567, likes: 89, isLiked: false, isBookmarked: false,
    commentCount: 34, images: [], hashtags: ['주말', '클럽', '일상'],
    readTimeMin: 1, isPopular: true, isReported: false,
    comments: [makeComment('c3', 'f2', 'solo', '저도요 ㅋㅋ 혼클 마스터입니다')],
  },
  {
    id: 'f3', board: 'free', title: '나이트라이프 입문 3개월차 소감',
    content: '처음에는 클럽이 뭔지도 몰랐는데 3개월 다니다 보니 이제 좀 알겠네요. 음악 장르도 구분되고, 각 클럽의 분위기 차이도 느껴지고... 이 글에서는 3개월간 배운 것들을 정리해볼게요. 첫째, 혼자 가도 괜찮습니다. 둘째, 드레스코드는 생각보다 중요합니다. 셋째, 수분 보충을 꼭 하세요. 넷째, 귀마개를 챙기세요. 다섯째, 첫 잔은 천천히.',
    excerpt: '처음에는 클럽이 뭔지도 몰랐는데 3개월 다니다 보니...',
    author: authors.newbie, createdAt: '2026-03-12T15:00:00Z',
    views: 891, likes: 156, isLiked: false, isBookmarked: false,
    commentCount: 42, images: [], hashtags: ['입문', '후기', '팁'],
    readTimeMin: 2, isPopular: true, isReported: false,
    comments: [makeComment('c4', 'f3', 'clubmaster', '좋은 정리네요! 귀마개 팁 진짜 중요합니다')],
  },
  {
    id: 'f4', board: 'free', title: '해운대 여름 시즌 시작되면 어디가 제일 좋나요',
    content: '여름에 부산 해운대 갈 계획인데, 클럽이나 바 추천 부탁드려요. 오션뷰가 있는 곳이면 더 좋겠습니다.',
    excerpt: '여름에 부산 해운대 갈 계획인데...',
    author: authors.busan, createdAt: '2026-03-12T10:00:00Z',
    views: 234, likes: 45, isLiked: false, isBookmarked: false,
    commentCount: 23, images: [], hashtags: ['해운대', '부산', '여름'],
    readTimeMin: 1, isPopular: false, isReported: false,
    comments: [makeComment('c5', 'f4', 'tour', '부산연산동물나이트 강추! 오션뷰 최고')],
  },
  {
    id: 'f5', board: 'free', title: '혼자 클럽 가본 사람 있나요? 후기 공유',
    content: '처음으로 혼자 클럽에 가봤습니다. 솔직히 갈 때는 엄청 긴장했는데, 막상 가보니 생각보다 혼자 오신 분들이 많더라고요. 음악에 집중할 수 있어서 오히려 더 좋았어요. 바 카운터에서 음료 마시면서 분위기 즐기다가 댄스플로어로 나가는 패턴이 편했습니다. 혼클 고민하시는 분들 용기 내보세요.',
    excerpt: '처음으로 혼자 클럽에 가봤습니다...',
    author: authors.solo, createdAt: '2026-03-11T22:00:00Z',
    views: 1203, likes: 234, isLiked: false, isBookmarked: false,
    commentCount: 78, images: [], hashtags: ['혼클', '후기', '용기'],
    readTimeMin: 2, isPopular: true, isReported: false,
    comments: [
      makeComment('c6', 'f5', 'newbie', '용기 얻고 갑니다!'),
      makeComment('c7', 'f5', 'weekend', '혼클 대선배시네요'),
    ],
  },
  {
    id: 'f6', board: 'free', title: '요즘 홍대 트렌드가 바뀐 것 같아요',
    content: '예전에는 인디 음악 위주였는데 요즘은 EDM 비중이 많이 높아진 느낌. 홍대만의 색깔이 조금 줄어든 것 같아서 아쉽기도 하네요. 여러분은 어떻게 생각하세요?',
    excerpt: '예전에는 인디 음악 위주였는데...',
    author: authors.hongdae, createdAt: '2026-03-11T14:00:00Z',
    views: 456, likes: 67, isLiked: false, isBookmarked: false,
    commentCount: 29, images: [], hashtags: ['홍대', '트렌드', '인디'],
    readTimeMin: 1, isPopular: false, isReported: false,
    comments: [],
  },
  {
    id: 'f7', board: 'free', title: '클럽 음악 장르별 추천 부탁드립니다',
    content: 'EDM은 알겠는데 테크노, 하우스, 트랜스 차이를 잘 모르겠어요. 각 장르별로 추천 클럽 알려주시면 감사하겠습니다. 강남이나 홍대 위주로요.',
    excerpt: 'EDM은 알겠는데 테크노, 하우스, 트랜스 차이를...',
    author: authors.music, createdAt: '2026-03-10T20:00:00Z',
    views: 678, likes: 98, isLiked: false, isBookmarked: false,
    commentCount: 51, images: [], hashtags: ['장르', 'EDM', '테크노'],
    readTimeMin: 1, isPopular: true, isReported: false,
    comments: [makeComment('c8', 'f7', 'clubmaster', '테크노는 압구정클럽 인트로, 하우스는 청담클럽 아르쥬, EDM은 강남클럽 레이스가 대표적이에요')],
  },
  {
    id: 'f8', board: 'free', title: '이태원 vs 청담 라운지 고민 중',
    content: '데이트 장소로 라운지를 생각 중인데, 이태원과 청담 중 어디가 더 좋을까요? 분위기 좋고 조용한 곳으로 가고 싶습니다.',
    excerpt: '데이트 장소로 라운지를 생각 중인데...',
    author: authors.lounge, createdAt: '2026-03-10T16:00:00Z',
    views: 345, likes: 34, isLiked: false, isBookmarked: false,
    commentCount: 18, images: [], hashtags: ['이태원', '청담', '라운지', '데이트'],
    readTimeMin: 1, isPopular: false, isReported: false,
    comments: [],
  },
];

// ── Review Posts ────────────────────────────────────────
export const reviewPosts: Post[] = [
  {
    id: 'r1', board: 'reviews', title: '강남클럽 레이스 주말 방문 후기',
    content: '사운드 시스템이 정말 좋았고, DJ 라인업도 만족스러웠습니다. VIP 테이블 서비스도 깔끔하고 직원들이 친절했어요. 다만 주말이라 사람이 엄청 많아서 댄스플로어는 좀 답답했습니다. 가격대는 VIP 테이블 80만원 정도였고, 입장료는 3만원이었습니다. 전체적으로 만족스러운 경험이었고 다음에 또 가고 싶습니다.',
    excerpt: '사운드 시스템이 정말 좋았고, DJ 라인업도 만족스러웠습니다...',
    author: authors.clubmaster, createdAt: '2026-03-13T10:00:00Z',
    views: 567, likes: 89, isLiked: false, isBookmarked: false,
    commentCount: 23, images: [], hashtags: ['강남', '레이스', '클럽후기'],
    readTimeMin: 2, isPopular: true, isReported: false,
    venueTag: '강남클럽 레이스', venueRegion: '강남', rating: 4.5,
    comments: [makeComment('cr1', 'r1', 'party', '강남클럽 레이스 VIP 서비스 진짜 좋죠')],
  },
  {
    id: 'r2', board: 'reviews', title: '강남클럽 사운드 금요일 밤 솔직 리뷰',
    content: '음악은 항상 좋은데 주말에는 사람이 너무 많아서 조금 답답할 수 있어요. 평일에 가면 훨씬 쾌적하게 즐길 수 있습니다. 사운드 퀄리티는 강남 클럽 중에서 상위권이고, DJ 믹싱도 안정적이에요. 입장료 1만5천원 정도.',
    excerpt: '음악은 항상 좋은데 주말에는 사람이 너무 많아서...',
    author: authors.hongdae, createdAt: '2026-03-12T20:00:00Z',
    views: 345, likes: 67, isLiked: false, isBookmarked: false,
    commentCount: 31, images: [], hashtags: ['강남', '사운드', '클럽후기'],
    readTimeMin: 1, isPopular: false, isReported: false,
    venueTag: '강남클럽 사운드', venueRegion: '강남', rating: 4.0,
    comments: [],
  },
  {
    id: 'r3', board: 'reviews', title: '강남클럽 레이스 처음 가봤는데...',
    content: '분위기가 정말 다르더라고요. 라이브 밴드 퀄리티가 상당하고, 연령대가 좀 있어서 차분하게 즐길 수 있었습니다. 댄스홀이 넓어서 답답한 느낌 없이 춤출 수 있었고, 무료 댄스 레슨도 진행하더라고요. 정장 입고 가야 해서 준비는 좀 필요했지만 그만큼 격식 있는 분위기였습니다.',
    excerpt: '분위기가 정말 다르더라고요. 라이브 밴드 퀄리티가 상당하고...',
    author: authors.newbie, createdAt: '2026-03-12T15:00:00Z',
    views: 789, likes: 145, isLiked: false, isBookmarked: false,
    commentCount: 38, images: [], hashtags: ['강남', '클럽', '첫방문'],
    readTimeMin: 2, isPopular: true, isReported: false,
    venueTag: '강남클럽 레이스', venueRegion: '강남', rating: 4.8,
    comments: [makeComment('cr3', 'r3', 'dance', '강남클럽 레이스 밴드 퀄리티 진짜 인정합니다')],
  },
  {
    id: 'r4', board: 'reviews', title: '부산연산동물나이트 오션뷰 후기',
    content: '테라스에서 보는 오션뷰가 진짜 압도적입니다. 밤에 해운대 바다를 배경으로 춤추는 건 정말 특별한 경험이에요. 여름 되면 사람 엄청 많아질 듯. 가격은 입장료 5만원에 테이블 80만원 정도. 부산 여행 중이라면 꼭 가보세요.',
    excerpt: '테라스에서 보는 오션뷰가 진짜 압도적입니다...',
    author: authors.busan, createdAt: '2026-03-11T18:00:00Z',
    views: 456, likes: 56, isLiked: false, isBookmarked: false,
    commentCount: 19, images: [], hashtags: ['부산', '오션뷰', '나이트후기'],
    readTimeMin: 1, isPopular: false, isReported: false,
    venueTag: '부산연산동물나이트', venueRegion: '부산', rating: 4.2,
    comments: [],
  },
  {
    id: 'r5', board: 'reviews', title: '일산명월관요정 비즈니스 접대 이용 후기',
    content: '거래처 접대로 이용했는데 정말 만족스러웠습니다. 한정식 코스가 15가지나 되어서 음식만으로도 대접받는 느낌이고, 국악 라이브 연주가 분위기를 한층 높여줬어요. 프라이빗 룸이 넓어서 대화하기 편했고, 직원분들 서비스가 정말 프로페셔널했습니다. 주차도 편하고 마두역에서 가까워서 접근성도 좋아요.',
    excerpt: '거래처 접대로 이용했는데 정말 만족스러웠습니다...',
    author: authors.vip, createdAt: '2026-03-11T12:00:00Z',
    views: 678, likes: 123, isLiked: false, isBookmarked: false,
    commentCount: 28, images: [], hashtags: ['일산요정', '명월관', '접대', '한정식'],
    readTimeMin: 2, isPopular: true, isReported: false,
    venueTag: '일산명월관요정', venueRegion: '일산', rating: 4.9,
    comments: [makeComment('cr5', 'r5', 'tour', '명월관 한정식 퀄리티는 서울 대비 가성비 최고입니다')],
  },
];

// ── Party Posts ─────────────────────────────────────────
export const partyPosts: Post[] = [
  {
    id: 'p1', board: 'party', title: '이번 토요일 강남 클럽 같이 가실 분!',
    content: '이번 토요일 강남클럽 레이스 VIP 테이블 잡아놨는데, 같이 갈 멤버 구합니다. 비용은 N빵 예정이고, 술은 각자 취향대로. 20대 중후반~30대 초반 남녀 모두 환영합니다.',
    excerpt: '이번 토요일 강남클럽 레이스 VIP 테이블 잡아놨는데...',
    author: authors.party, createdAt: '2026-03-13T14:00:00Z',
    views: 456, likes: 34, isLiked: false, isBookmarked: false,
    commentCount: 12, images: [], hashtags: ['강남', '레이스', 'N빵'],
    readTimeMin: 1, isPopular: false, isReported: false,
    partyDate: '2026-03-15', partyRegion: '강남', currentMembers: 3, maxMembers: 6,
    ageRange: '20대 중반~30대 초반', partyStatus: '모집중', totalBudget: 600000,
    comments: [makeComment('cp1', 'p1', 'weekend', '참여 희망합니다! 30살 남자예요')],
  },
  {
    id: 'p2', board: 'party', title: '홍대 클럽 투어 멤버 구합니다 (3/21)',
    content: '강남 클럽 3~4곳 돌아볼 예정입니다. 강남클럽 사운드 → 압구정클럽 하입 → 압구정클럽 인트로 루트로 생각 중이에요. 중간에 포차에서 간단히 먹고 이동할 계획. 교통비 제외 1인당 10만원 정도 예상.',
    excerpt: '강남 클럽 3~4곳 돌아볼 예정입니다...',
    author: authors.hongdae, createdAt: '2026-03-13T10:00:00Z',
    views: 345, likes: 45, isLiked: false, isBookmarked: false,
    commentCount: 8, images: [], hashtags: ['홍대', '클럽투어', 'N빵'],
    readTimeMin: 1, isPopular: false, isReported: false,
    partyDate: '2026-03-21', partyRegion: '홍대', currentMembers: 4, maxMembers: 8,
    ageRange: '20대', partyStatus: '모집중', totalBudget: 800000,
    comments: [],
  },
  {
    id: 'p3', board: 'party', title: '해운대 주말 파티 동행 모집',
    content: '부산 부산연산동물나이트 갈 계획입니다. 금요일 저녁에 출발해서 토요일 오전까지 놀 예정. 숙소는 근처에 잡아둘게요. 비용 N빵.',
    excerpt: '부산 부산연산동물나이트 갈 계획입니다...',
    author: authors.busan, createdAt: '2026-03-12T20:00:00Z',
    views: 234, likes: 23, isLiked: false, isBookmarked: false,
    commentCount: 6, images: [], hashtags: ['해운대', '부산', '나이트'],
    readTimeMin: 1, isPopular: false, isReported: false,
    partyDate: '2026-03-22', partyRegion: '해운대', currentMembers: 2, maxMembers: 5,
    ageRange: '20대~30대', partyStatus: '모집중', totalBudget: 500000,
    comments: [],
  },
  {
    id: 'p4', board: 'party', title: '이태원 라운지 바 호핑 같이 하실 분',
    content: '이태원 라운지 바 3곳 정도 돌면서 칵테일 한 잔씩 마시는 코스입니다. 분위기 좋은 곳 위주로 선정했어요. 가볍게 즐기실 분 환영.',
    excerpt: '이태원 라운지 바 3곳 정도 돌면서...',
    author: authors.lounge, createdAt: '2026-03-12T15:00:00Z',
    views: 178, likes: 28, isLiked: false, isBookmarked: false,
    commentCount: 15, images: [], hashtags: ['이태원', '라운지', '바호핑'],
    readTimeMin: 1, isPopular: false, isReported: false,
    partyDate: '2026-03-16', partyRegion: '이태원', currentMembers: 5, maxMembers: 5,
    ageRange: '20대 후반~30대', partyStatus: '마감', totalBudget: 250000,
    comments: [],
  },
  {
    id: 'p5', board: 'party', title: '청담 나이트 첫 방문 같이 가요',
    content: '나이트 문화가 궁금해서 첫 방문 예정인데, 경험 있으신 분과 같이 가면 좋겠습니다. 댄스 못 춰도 괜찮은 분 환영.',
    excerpt: '나이트 문화가 궁금해서 첫 방문 예정인데...',
    author: authors.newbie, createdAt: '2026-03-11T18:00:00Z',
    views: 156, likes: 19, isLiked: false, isBookmarked: false,
    commentCount: 4, images: [], hashtags: ['청담', '나이트', '첫방문'],
    readTimeMin: 1, isPopular: false, isReported: false,
    partyDate: '2026-03-29', partyRegion: '강남', currentMembers: 2, maxMembers: 4,
    ageRange: '30대', partyStatus: '모집중', totalBudget: 400000,
    comments: [],
  },
];

// ── Tips Posts ──────────────────────────────────────────
export const tipsPosts: Post[] = [
  {
    id: 't1', board: 'tips', title: '클럽 처음 가는 사람을 위한 완벽 가이드',
    content: '클럽 문화가 처음이라면 이 글 하나로 충분합니다. 입장부터 퇴장까지 알아야 할 모든 것을 정리했어요. 1) 신분증 필수, 2) 드레스코드 사전 확인, 3) 현금+카드 둘 다 준비, 4) 귀마개 챙기기, 5) 택시비 미리 확보, 6) 수분 보충 중요, 7) 친구 연락처 공유, 8) 음악에 몸을 맡기기, 9) 어색해도 웃기, 10) 즐기기.',
    excerpt: '클럽 문화가 처음이라면 이 글 하나로 충분합니다...',
    author: authors.clubmaster, createdAt: '2026-03-10T10:00:00Z',
    views: 2345, likes: 456, isLiked: false, isBookmarked: false,
    commentCount: 89, images: [], hashtags: ['입문', '가이드', '필독'],
    readTimeMin: 3, isPopular: true, isReported: false,
    tipCategory: '입문', bookmarks: 234,
    comments: [makeComment('ct1', 't1', 'newbie', '진짜 도움 됐어요 감사합니다!')],
  },
  {
    id: 't2', board: 'tips', title: 'VIP 테이블 200% 활용하는 방법',
    content: 'VIP 테이블 예약의 장단점, 가성비 좋은 이용법, 그리고 테이블 매너까지 알려드립니다. 인원수에 맞는 테이블 선택이 가장 중요하고, 음료 주문은 한 번에 하는 것보다 나눠서 하는 게 좋습니다.',
    excerpt: 'VIP 테이블 예약의 장단점, 가성비 좋은 이용법...',
    author: authors.vip, createdAt: '2026-03-09T14:00:00Z',
    views: 1567, likes: 312, isLiked: false, isBookmarked: false,
    commentCount: 56, images: [], hashtags: ['VIP', '테이블', '가성비'],
    readTimeMin: 2, isPopular: true, isReported: false,
    tipCategory: '고급', bookmarks: 189,
    comments: [],
  },
  {
    id: 't3', board: 'tips', title: '나이트에서 자연스럽게 즐기는 법',
    content: '처음이라 어색한 분들을 위한 팁. 음악에 몸을 맡기는 법부터 시작해보세요. 완벽하게 추려고 하지 말고, 리듬에 살짝 몸을 흔드는 것부터 시작하면 자연스럽게 됩니다.',
    excerpt: '처음이라 어색한 분들을 위한 팁...',
    author: authors.dance, createdAt: '2026-03-08T10:00:00Z',
    views: 1234, likes: 278, isLiked: false, isBookmarked: false,
    commentCount: 43, images: [], hashtags: ['나이트', '댄스', '초보'],
    readTimeMin: 2, isPopular: true, isReported: false,
    tipCategory: '문화', bookmarks: 156,
    comments: [],
  },
  {
    id: 't4', board: 'tips', title: '지역별 나이트라이프 특징 총정리',
    content: '강남, 홍대, 이태원, 청담, 해운대... 각 지역마다 다른 분위기와 특징을 한눈에 비교해보세요. 강남은 VIP 문화, 홍대는 자유분방, 이태원은 글로벌, 청담은 프리미엄, 해운대는 리조트 느낌.',
    excerpt: '강남, 홍대, 이태원, 청담, 해운대...',
    author: authors.tour, createdAt: '2026-03-07T16:00:00Z',
    views: 2100, likes: 523, isLiked: false, isBookmarked: false,
    commentCount: 67, images: [], hashtags: ['지역별', '비교', '정보'],
    readTimeMin: 3, isPopular: true, isReported: false,
    tipCategory: '정보', bookmarks: 312,
    comments: [],
  },
  {
    id: 't5', board: 'tips', title: '택시 & 대리운전 스마트하게 이용하기',
    content: '새벽 시간 안전하게 귀가하는 방법. 택시 앱 팁부터 대리운전 이용까지. 카카오T 예약은 마감 1시간 전에 잡아두세요. 대리운전은 출발 30분 전에 호출하면 대기 시간을 줄일 수 있습니다.',
    excerpt: '새벽 시간 안전하게 귀가하는 방법...',
    author: authors.safe, createdAt: '2026-03-06T12:00:00Z',
    views: 890, likes: 198, isLiked: false, isBookmarked: false,
    commentCount: 34, images: [], hashtags: ['안전', '귀가', '택시'],
    readTimeMin: 2, isPopular: false, isReported: false,
    tipCategory: '안전', bookmarks: 145,
    comments: [],
  },
];

// ── Fashion Posts ───────────────────────────────────────
export const fashionPosts: Post[] = [
  {
    id: 'fa1', board: 'fashion', title: '클럽별 드레스코드 완벽 정리 2026',
    content: '각 클럽별 드레스코드를 정리했습니다. 강남클럽 레이스는 스마트 캐주얼, 압구정클럽 하입은 자유, 압구정클럽 인트로는 완전 자유. 나이트는 대부분 정장 필수입니다. 라운지는 매장마다 다르니 사전 확인 필수.',
    excerpt: '각 클럽별 드레스코드를 정리했습니다...',
    author: authors.fashion, createdAt: '2026-03-12T10:00:00Z',
    views: 2345, likes: 567, isLiked: false, isBookmarked: false,
    commentCount: 78, images: [], hashtags: ['드레스코드', '클럽', '2026'],
    readTimeMin: 3, isPopular: true, isReported: false,
    fashionCategory: '드레스코드', fashionTags: ['클럽', '드레스코드', '기본'],
    comments: [],
  },
  {
    id: 'fa2', board: 'fashion', title: '라운지 데이트룩 스타일링 제안',
    content: '라운지 데이트에 적합한 코디를 소개합니다. 남성은 네이비 셋업 + 화이트 셔츠가 무난하고, 여성은 원피스나 블라우스 + 슬랙스 조합이 좋습니다.',
    excerpt: '라운지 데이트에 적합한 코디를 소개합니다...',
    author: authors.style, createdAt: '2026-03-11T14:00:00Z',
    views: 1234, likes: 423, isLiked: false, isBookmarked: false,
    commentCount: 56, images: [], hashtags: ['라운지', '데이트', '코디'],
    readTimeMin: 2, isPopular: true, isReported: false,
    fashionCategory: '스타일링', fashionTags: ['라운지', '데이트', '셋업'],
    comments: [],
  },
  {
    id: 'fa3', board: 'fashion', title: '여름 클럽 패션 - 시원하면서 멋지게',
    content: '여름 클럽 패션은 통기성이 핵심입니다. 린넨 셔츠나 얇은 면 소재 반팔이 좋고, 하의는 슬랙스나 면바지 추천. 반바지는 매장에 따라 입장 제한될 수 있어요.',
    excerpt: '여름 클럽 패션은 통기성이 핵심입니다...',
    author: authors.fashion, createdAt: '2026-03-10T10:00:00Z',
    views: 890, likes: 345, isLiked: false, isBookmarked: false,
    commentCount: 41, images: [], hashtags: ['여름', '클럽패션', '린넨'],
    readTimeMin: 2, isPopular: false, isReported: false,
    fashionCategory: '시즌', fashionTags: ['여름', '클럽', '캐주얼'],
    comments: [],
  },
  {
    id: 'fa4', board: 'fashion', title: '나이트 정장 스타일 가이드 (남성편)',
    content: '나이트클럽은 대부분 정장 또는 세미 포멀을 요구합니다. 네이비/차콜 슈트가 기본이고, 넥타이는 선택. 구두는 필수이며, 편한 로퍼를 추천합니다.',
    excerpt: '나이트클럽은 대부분 정장 또는 세미 포멀을 요구합니다...',
    author: authors.style, createdAt: '2026-03-09T16:00:00Z',
    views: 678, likes: 289, isLiked: false, isBookmarked: false,
    commentCount: 34, images: [], hashtags: ['나이트', '정장', '남성패션'],
    readTimeMin: 2, isPopular: false, isReported: false,
    fashionCategory: '남성', fashionTags: ['나이트', '정장', '남성'],
    comments: [],
  },
];

// ── QnA Posts ──────────────────────────────────────────
export const qnaPosts: Post[] = [
  {
    id: 'q1', board: 'qna', title: '클럽 첫 방문인데 혼자 가도 괜찮을까요?',
    content: '클럽에 관심이 생겼는데 주변에 같이 갈 사람이 없어요. 혼자 가도 이상하지 않을까요?',
    excerpt: '클럽에 관심이 생겼는데...',
    author: authors.newbie, createdAt: '2026-03-13T18:00:00Z',
    views: 567, likes: 45, isLiked: false, isBookmarked: false,
    commentCount: 8, images: [], hashtags: ['초보', '클럽', '혼자'],
    readTimeMin: 1, isPopular: false, isReported: false,
    isSolved: true, answerCount: 8,
    comments: [makeComment('cq1', 'q1', 'solo', '전혀 이상하지 않아요! 혼클족 엄청 많습니다. 용기 내세요!')],
  },
  {
    id: 'q2', board: 'qna', title: '강남과 홍대 클럽 분위기 차이가 어떤가요?',
    content: '둘 다 안 가봤는데, 분위기 차이가 궁금합니다. 20대 후반 남자인데 어디가 더 맞을까요?',
    excerpt: '둘 다 안 가봤는데...',
    author: authors.music, createdAt: '2026-03-13T12:00:00Z',
    views: 890, likes: 67, isLiked: false, isBookmarked: false,
    commentCount: 12, images: [], hashtags: ['강남', '홍대', '비교'],
    readTimeMin: 1, isPopular: true, isReported: false,
    isSolved: true, answerCount: 12,
    comments: [makeComment('cq2', 'q2', 'clubmaster', '강남은 VIP 문화가 강하고 좀 더 고급진 느낌, 홍대는 자유분방하고 인디적 감성이 강해요')],
  },
  {
    id: 'q3', board: 'qna', title: '나이트클럽 입장 시 신분증 꼭 필요한가요?',
    content: '신분증 없이도 입장 가능한 곳이 있나요?',
    excerpt: '신분증 없이도 입장 가능한 곳이...',
    author: authors.busan, createdAt: '2026-03-12T20:00:00Z',
    views: 345, likes: 23, isLiked: false, isBookmarked: false,
    commentCount: 5, images: [], hashtags: ['입장', '신분증', '필수'],
    readTimeMin: 1, isPopular: false, isReported: false,
    isSolved: true, answerCount: 5,
    comments: [makeComment('cq3', 'q3', 'clubmaster', '법적으로 신분증 확인이 의무이므로 반드시 필요합니다')],
  },
  {
    id: 'q4', board: 'qna', title: '호빠 이용 에티켓이 궁금합니다',
    content: '처음 가보려는데 기본적인 에티켓을 알고 싶어요.',
    excerpt: '처음 가보려는데...',
    author: authors.lounge, createdAt: '2026-03-11T10:00:00Z',
    views: 456, likes: 28, isLiked: false, isBookmarked: false,
    commentCount: 4, images: [], hashtags: ['호빠', '에티켓'],
    readTimeMin: 1, isPopular: false, isReported: false,
    isSolved: false, answerCount: 4,
    comments: [],
  },
  {
    id: 'q5', board: 'qna', title: '요정은 어떤 곳인가요? 처음 가보려는데',
    content: '요정이 어떤 곳인지, 가격대는 어떤지, 복장은 어떻게 해야 하는지 궁금합니다.',
    excerpt: '요정이 어떤 곳인지...',
    author: authors.newbie, createdAt: '2026-03-10T14:00:00Z',
    views: 234, likes: 19, isLiked: false, isBookmarked: false,
    commentCount: 3, images: [], hashtags: ['요정', '초보', '가격'],
    readTimeMin: 1, isPopular: false, isReported: false,
    isSolved: false, answerCount: 3,
    comments: [makeComment('cq5', 'q5', 'vip', '요정은 한정식+국악 공연이 있는 전통 접대 공간이에요. 세미포멀 이상 복장 추천.')],
  },
];

export function getAllPosts(): Post[] {
  return [...freePosts, ...reviewPosts, ...partyPosts, ...tipsPosts, ...fashionPosts, ...qnaPosts];
}

export function getPopularPosts(limit = 5): Post[] {
  return getAllPosts()
    .filter((p) => p.isPopular)
    .sort((a, b) => b.likes - a.likes)
    .slice(0, limit);
}
