export declare const HERO_FILE_VER: Record<string, string>;
export declare const OG_FILE_VER: Record<string, string>;
export declare const OG_DEFAULT_VER: string;
export declare function heroVer(slug: string): string;
export declare function ogVer(slug: string): string;
export declare function cardSrc(slug: string): string;
export declare const OG_OWN_PAGE_VER: Record<string, string>;
export declare function ogOwnVer(slug: string): string;
export declare function cardOwnSrc(slug: string): string;
export declare const MAGAZINE_OG: Record<string, string>;
