# 놀쿨 한국1위 시리즈 파트1 v2 — 3도구 전 기능 + AEO·GEO + 전 페이지 기준선 전수 조사 (2026-08-08~09)

> **성격**: 읽기 전용 감사 보고서. 코드·콘텐츠·설정 수정 0, 배포용 변경 0 (이 보고서 파일 커밋 1회만).
> **목적**: 9/1 월간 판정(H1 CTR 2.0% · H2 전화 30회 · H3 세션당 3.1)을 오염시키지 않으면서, "한국 유흥정보 1위"로 가는 처방의 재료를 전수 수집. 처방은 별도 발행.
> **소스 표기**: [직접] = 이번 조사 API/스캔 실측 · [축적] = 기존 자동화 런로그·8/2 월간 사이클 산출물 재사용 · ⚠️ = 미확인/산출 불가(사유 병기).
> **오염 방지 실행 내역**: v1 = ga4-gsc-full-dump dispatch 1회(읽기 전용)·헤드리스 12페이지(webdriver 차단으로 GA 오염 0)·웹 리서치. v2 추가 = GH 런로그/아티팩트 회수(curl GET만)·dist 663장 정적 스캔·WebSearch 6질문. **Clarity API 신규 호출 0회(일 한도 10 온존, 워치 자체 4/10만 사용 확인)** · 신규 dispatch 0 · 사이트 크롤 0.

---

## [0] 전 페이지 명부 — 총 **663장** (빌드 산출물 dist/ index.html 전수, 2026-08-05 빌드)

**663 = sitemap 색인 대상 472 + 비색인 191** (tag 172 = 의도된 noindex 게이트 · admin 10 · 로그인/마이/검색 등 앱 전용 9). sitemap 유령 URL(빌드 산출물 없는 loc) **0건** [직접].

| 유형 | 장수 | 내역 |
|---|---|---|
| venue 상세 | **123** | nights 61 · clubs 38 · hoppa 18 · lounges 3 · rooms 2 · yojeong 1 (전원 verified_open) |
| 카테고리 허브 | 7 | /nights /clubs /hoppa /rooms /yojeong /lounges + 홈 |
| 카테고리×지역 허브 | 18 | clubs 15 · rooms 2 · yojeong 1 |
| region 허브 | 115 | 한글 URL (48지역 × 카테고리 교차) |
| near(역세권) | 55 | /near/{역명} |
| tag | 206 | 색인 34 + noindex 172 |
| magazine | 60 | 허브 1 + 글 59 |
| community | 9+8 | 게시판 7종+가이드라인+허브 · lounge(라운지 게시판) 8 |
| new / best | 6+5 | 카테고리별 신규·인기 집계 |
| guide | 2 | /guide/ilsan-yojeong 포함 |
| admin | 10 | 비색인 |
| 기타 단일 | 37 | 홈·법적고지·랭킹·룰렛·퀴즈·리드 3장 등 |

이후 [1]~[8] 모든 전수 조사는 이 663장(색인 대상은 472장)을 기준으로 한다.

---

## [1] 3도구 46계열 전수 표

### GA4 23계열 (property 540830544 · 28d 2026-07-11~08-09 · ga4-gsc-full-dump 08-08 런)

| # | 계열 | 대표 수치 | 포인트 수 | 소스 |
|---|---|---|---|---|
| 1 | 페이지별 조회수 | 1위 /magazine/daejeon-night-guide/ 238PV · /nights/ 191 · 홈 182 | 480행 | [직접] |
| 2 | 평균 참여시간 | 재방문 216.3s vs 신규 90.1s(2.4배) · 한국 세션 110.8s | 차원별 전수 | [직접] |
| 3 | 이탈률 | 한국 39.5% · mobile 47.6% vs desktop 27.4% | 480행+ | [직접] |
| 4 | 세션당 페이지 | **2.65** (PV 4,906 ÷ 세션 1,848) | 29일 | [직접-파생] |
| 5 | 신규/재방문 사용자 | 신규 1,595명 vs 재방문 101명(세션 189 = 10.6%) | 4 | [직접] |
| 6 | 채널(소스/미디엄) | google/organic 1,347 · direct 340 · bing 56 · **chatgpt.com/ai-assistant 16** | 16 | [직접] |
| 7 | D1/D7/D30 리텐션 | 코호트 W1 1.3% / W2 0.7% (08-02 월간 산출물) — D30 형식 산출물 없음 | 2 | [축적]·⚠️D30 |
| 8 | 재방문 세그먼트 행동 | 재방문 참여율 65.1% vs 신규 56.2% · 체류 2.4배 | 4 | [직접] |
| 9 | 랜딩 페이지 | 대전가이드 153세션(참여율 70.6%) · **/clubs 46세션(참여율 4.3%)** | 100행 | [직접] |
| 10 | 종료 페이지 | exitPage 차원 미덤프 — 페이지별 bounceRate로만 대체 가능 | 0 | ⚠️ |
| 11 | 시간대별 | 피크 22시 140 · 21시 124 · **04시 130(참여율 27.7% = 봇대)** | 24 | [직접] |
| 12 | 도시별 | 서울 670 · 부산 203 · 고양 89 · 대전 87(참여율 73.6% 최고) | 30행 | [직접] |
| 13 | 기기별 | mobile 1,423(75%) · desktop 434 · tablet 39 | 3 | [직접] |
| 14 | 참여율 | desktop 72.6% vs mobile 52.4% · 최근 정상일(08-07) 57.5% | 차원별 | [직접] |
| 15 | 이벤트 사용량 전수 | 13종: page_view 4,906 · session_start 1,829 · user_engagement 1,621 · first_visit 1,595 | 13 | [직접] |
| 16 | phone_click 실적 | **6회 / 2명** (08-02 첫 계측 후 ~6일) | 1 | [직접] |
| 17 | 채널별 리텐션 품질 | 채널×참여율: organic 61.2% · direct 35.0% · AI Assistant 43.8% · bing 80.4% | 7 | [직접](신규/재방문 교차 미덤프) |
| 18 | 사이트 내 검색어 | search 34회/13명 · view_search_results 2회 — 검색어 텍스트는 searchTerm 차원 미덤프 | 2 | [직접]카운트·⚠️텍스트 |
| 19 | 참여세션 수 | ≈1,023 (일별 참여율×세션 합산) | 29 | [직접-파생] |
| 20 | 사용자당 세션 | 1.13 (1,829회/1,630명) | 1 | [직접] |
| 21 | dauPerMau | **1.106%** · wauPerMau 7.60% (습관성 기준선) | 2 | [축적 08-02] |
| 22 | 회원/로그인 디멘션 | 커스텀 디멘션 미덤프 — 간접 실측: login 43회/3명 · sign_up 1회 | 2 | ⚠️(간접만 [직접]) |
| 23 | scroll_100 완독 | 328회/183명 (6.7%/PV · keyEvent 등록 확인) | 2 | [직접] |

### GSC 11계열 (nolcool.com · 28d 2026-07-09~08-06)

| # | 계열 | 대표 수치 | 포인트 수 | 소스 |
|---|---|---|---|---|
| 24 | 노출 | **24,519**(기기 차원 합 = 전수) / 쿼리 차원 합 13,825 | 3/845행 | [직접] |
| 25 | 클릭 | **1,468** / 쿼리 차원 848 (익명화 격차 42% — 부록 참조) | 3/845 | [직접] |
| 26 | CTR | **6.0%** · mobile 6.2% vs desktop 5.1% | 3 | [직접] |
| 27 | 평균순위 | 한국 8.9 · mobile 8.4 vs desktop 11.2 | 30/3 | [직접] |
| 28 | CTR 미달 목록 | 페이지 10곳·쿼리 9건 전수 산출(아래 별표) — 최대 /nights/daejeononenight 무슬래시 882노출·CTR 0.7%·순위 2.8 | 339/845행 | [직접-파생] |
| 29 | 색인 검사 | **색인 444 / 472 (94.1%)** · 미색인 28(발견-미색인 26·미인지 1·의도된 noindex 1) · 오류 0 | 472 전수 | [축적 08-03](08-08 job은 타임아웃 취소 ⚠️) |
| 30 | 기기/노출형태 | MOBILE 노출 79% | 3 | [직접]·⚠️searchAppearance 미호출 |
| 31 | 사이트맵 상태 | 472 URL 정합(dist 대조 유령 0) · 08-03 런이 재제출 204 확인 | 472 | [직접+축적]·⚠️API 상태 미호출 |
| 32 | 이미지 검색 | 클릭 59 / 노출 5,082 / CTR 1.16% (썸네일 전화합성 추적 기준선) | — | [축적 08-02] |
| 33 | 28일 추세 | 동일방식 직전(07-03~07-31) 대비 보합: 클릭 848↔847 · 노출 13,825↔13,785 | 2창 | [축적]·⚠️일별 시계열(date 차원) 미덤프 |
| 34 | 브랜드/논브랜드 | 브랜드('놀쿨\|nolcool') 쿼리 **0건** — 검색 유입 100% 논브랜드 | 845 전수 | [직접-파생] |

### Clarity 11계열 (xp3oiz8heq · clarity-daily-watch 축적 런로그 08-06/07/08 · 신규 API 콜 0)

| # | 계열 | 대표 수치 (08-08 ← 08-07 ← 08-06) | 분해 | 소스 |
|---|---|---|---|---|
| 35 | Rage click | 문제세션 1(1.43%)/이벤트 30 ← 1/27 ← 0 — URL: /nights/daejeonsevennight/, 08-07은 /magazine/daejeon-night-guide/ 27이벤트 | URL 샘플만·기기/브라우저 분해 없음 | [축적] |
| 36 | Dead click | 1세션(1.43%)/이벤트 **157** ← 6(8.11%)/78 ← 6(10.53%)/14 — 대전세븐 1세션 37이벤트 집중 | URL 샘플만·기기 분해 없음 | [축적] |
| 37 | Error click | 0 ← 0 ← 0 (3일 연속 0%) | — | [축적] |
| 38 | Quickback | ≈10세션(14.29%) ← 6(8.11%) ← 7(12.28%) — URL 3일 모두 홈 | URL 샘플만 | [축적] |
| 39 | 과잉 스크롤 | 0 ← 0 ← 0 | — | [축적] |
| 40 | 스크립트 에러 | 0 ← 0 ← 0 | — | [축적] |
| 41 | 스크롤 깊이 | **45.5% ← 50.9% ← 62.8% (하락세)** | 사이트 평균만 | [축적] |
| 42 | 활동/총시간 격차 | 66s/41s(활동 62%) ← 77s/48s(62%) ← 144s/102s(71%) | totals만 | [축적] |
| 43 | Traffic(봇 제외) | 실세션 48(봇 22/총 70) ← 54(봇 20/74) ← 29(봇 28/57) — Mobile/google 54 · Android · KR | Device×Source 있음 | [축적] |
| 44 | 인기 페이지 | 홈 20방문 ← 21 ← 17 · 타이틀 top 3일 연속 "대전 나이트 4곳—"(7/11/11세션) | top-1만 | [축적] |
| 45 | 리퍼러 | google.com 58 ← 58 ← 41 | top-1만 | [축적] |

세션당 페이지 교차검증: ⚠️ 산출 불가 — Traffic totals 로그에 PV 필드 미노출(스크립트 필드명 불일치). 수치 창작 안 함.

### 성능 1계열 (lighthouse-daily · 런 31274742570 · KST 08-09 04:34 실측 · 7페이지×PC/Mobile — ⚠️10페이지 목록 중 3개는 측정 대상에 없음)

| # | 계열 | 대표 수치 | 소스 |
|---|---|---|---|
| 46 | Lighthouse 모바일 | **perf 평균 70 — 7/7 전 페이지 목표 90 미달**(68~74) · 원인 = LCP 5.2~7.5s(Slow 4G lab) · CLS 0.000~0.016 전 페이지 통과 · a11y 99(유일 감점 /magazine/ color-contrast) · desktop 평균 96(94 미달 2: /lounges/ /rooms/) | [축적 08-09] |

Mobile 상세: / 69(LCP 7.47s) · /clubs/ 74(5.85s) · /nights/ 70(6.42s) · /lounges/ 70(7.20s) · /community/ 72(6.10s) · /magazine/ 68(5.22s·TBT 375ms) · /rooms/ 70(6.89s). CWV 실사용자(CrUX) 지표와 별개인 lab 수치 — INP는 lab 미측정(TBT 대용).

### [1] 별표 — GSC CTR 미달 전수 (노출≥100 & CTR<1%) [직접-파생]

페이지 10곳: /nights/daejeononenight(무슬래시) 882노출·0.7%·순위2.8 → /nights/daejeonsevennight/ 869·0.7%·8.3 → /nights/suyushampoonight/ 665·0.3%·11.5 → /nights/ilsanshampoonight/ 592·0.5%·9.9 → /nights/busanasiadnight/ 508·0.6%·11.5 → /clubs/itaewon/itaewonclub-utopia/ 407·0.98%·9.0 → /magazine/gangnam-octagon-guide/ 350·0.6%·8.7 → /nights/suwonchancenight/ 309·0%·14.1 → /nights/sangbonghangukgwannight/ 240·0%·16.1 → /near/신사/ 176·0%·9.1.

쿼리 9건: 수유 샴푸나이트 226·0.9% · 온천장 아시아드 나이트 225·0% · 수유샴푸나이트 205·0% · 이태원 유토피아 173·0.6% · **청주 클럽 162·0.6%·순위 5.2** · 일산샴푸나이트 113·0% · 일산 샴푸나이트 106·0% · 답십리 돈텔마마 104·0.96% · **대전 클럽 102·0%·순위 5.0**.

---

## [2] AEO·GEO 현황 (한국 기준 · dist 663장 전수 정적 스캔 [직접] + WebSearch 표본)

### ① 구조화 데이터 적용률·오류 (663장 전수)

| 항목 | 실측 |
|---|---|
| JSON-LD 보유 | **663/663 (100%)** · JSON.parse 실패 **0건** |
| root @type 분포 | BreadcrumbList 629 · **FAQPage 536(80.8%)** · CollectionPage 393 · NightClub 99 · WebPage 69 · Article 59 · ItemList 24 · BarOrPub 21 · DiscussionForumPosting 9 등 |
| NightClub류 필수 필드 | name·address 결손 0 · **telephone 결손 109/120** — 가짜번호 금지 규칙의 구조적 결과(실번호 확보 전 불가침) |
| canonical / og:image | 결손 **0/663 · 0/663** |

### ② 상단 직답형 구조 적용률 (AI 인용의 55%가 상단 30%에서 발생 → body 앞 30% 기준 전수)

| 카테고리 | n | .ssr-answer 직답 보유 | body 앞30% 내 직답 | 첫 H2 블록 평균 어절 |
|---|---|---|---|---|
| venue 상세 6종 | 123 | **123/123 (100%)** | 123 (body 22~30% 지점) | 113~251 (AIO 90~110 밴드 초과측) |
| tag / region / near | 376 | 0 | 0 | 25~35 (밴드 미달 — 집계형 설계) |
| magazine | 60 | 0 | 0 | 14 |
| 기타 | 104 | 0 | 0 | 7~35 |

→ **직답 구조는 venue 상세에 100% 완비, 집계·매거진 층은 0%** — GEO 표본(아래)에서 인용된 2건이 모두 venue 상세/매거진 본문 문장이라는 점과 교차하면, 상단 직답의 확장 여지는 매거진·region 층이 최대 공백.

### ③ robots · AI 크롤러 · llms.txt [직접]

- robots.txt: **Disallow 0줄 — 전 봇 Allow**. AI 크롤러 명시 허용: GPTBot·ChatGPT-User·OAI-SearchBot·PerplexityBot·ClaudeBot·anthropic-ai·Google-Extended·CCBot·Bytespider·Applebot-Extended·Meta-ExternalAgent·cohere-ai·Amazonbot·YouBot·PhindBot 등 **차단 0**.
- llms.txt 26.4KB(링크 222개) + llms-full.txt 208KB. sitemap 472 loc — 663−noindex 191 구조와 정합.

### ④ AI 검색 실측 표본 — 6질문 (WebSearch, ⚠️미국 geo — 한국 실SERP와 상이 가능. 구글 AI 개요·ChatGPT·Perplexity·네이버 큐는 도구 실측 불가)

| 질문 | nolcool 등장 | 상위 경쟁 |
|---|---|---|
| 일산 나이트 추천 | ❌ | 밤픽(bampick) · nightpick · 다음카페 나이트클럽가이드 |
| 대전 나이트 어디가 좋아 | ✅ **7위 + LLM 요약이 놀쿨 매거진 문장 발췌 인용** | 나무위키 · 디시 · 네이트판 |
| 강남 클럽 추천 | ❌ | 나무위키 · 틱톡 · 밤픽/강남클럽닷컴 |
| 일산 룸 어디 | ✅ **7위 + AI 요약 주 소스(삼중 차음재·주차 디테일)** | 다이닝코드 · cafe24/isweb 원페이지 위성 다수 |
| 일산 요정 명월관 | ❌ | 명월관 자체·위성 사이트 5+ 독점 |
| 여자끼리 호빠 처음 | ❌ | Threads 꿀팁 시리즈 · 에펨코리아 · 나무위키 |

**관측 사실**: 6문 중 2문에서 놀쿨이 실제 LLM 요약층에 발췌·인용됨(대전 나이트·일산 룸) — 인용된 건 모두 "구체 디테일 문장". 미등장 4문은 나무위키·커뮤니티·업소 위성 사이트가 점유.
**사장님 직접 확인용 질문 목록**(구글 AI 개요·ChatGPT·Perplexity·네이버 큐 4곳에 그대로 붙여넣기): ①일산 나이트 추천 ②대전 나이트 어디가 좋아 ③강남 클럽 추천 ④일산 룸 어디 ⑤일산 요정 명월관 ⑥여자끼리 호빠 처음 가는데 어디.

---

## [3] "한국 유흥정보 1위"의 측정 가능한 정의 후보 + 현재 기준선

### 정의 후보 3축

| 축 | 정의 | 현재값 근거 |
|---|---|---|
| D1. 검색 점유 | 비브랜드 핵심 키워드군(업종 6종 × 도시)에서 구글 1페이지 진입 쿼리 수·클릭 점유 | GSC 순위 실측 [직접] |
| D2. 유입 규모 | 월(28d) 검색 클릭·노출·CTR | GSC [직접] |
| D3. 정착 품질 | 재방문율·세션당 페이지·전화 클릭 | GA4 [직접] |

### D1 — 비브랜드 1페이지 진입 실측 [직접] (GSC 웹검색 28d)

- 상위 쿼리 845개 전수 중 **브랜드 쿼리 0개** — 유입 100% 비브랜드.
- **1페이지(평균순위 ≤10) 진입: 363쿼리(43%)** · 클릭 756/848(89%)·노출 10,099 담당. **TOP3 진입: 62쿼리** · 클릭 283(33%).

| 업종 키워드군 | 전체 쿼리 | 1페이지 쿼리(점유) | 1페이지 클릭 | 비고 |
|---|---|---|---|---|
| 나이트 | 445 | 187 (42%) | 525 | 절대 주력 — 클릭의 62% |
| 클럽 | 144 | 73 (51%) | 49 | 진입률 높은데 클릭 전환 약함 |
| 룸 | 8 | 3 (38%) | 34 | 쿼리 폭 얇음(업소 2곳) |
| 요정 | 10 | 9 (90%) | 26 | 진입률 최고(업소 1곳 집중) |
| 호빠 | 8 | 1 (13%) | 3 | **최약 축** — 업소 18곳인데 쿼리 8개 |
| 라운지 | 13 | 2 (15%) | 0 | 클릭 0 — 사실상 미점유 |
| 기타(업소명·지명) | 240 | — | 164 | 일산명월관·대구 바밤바·창원룰루랄라 등 엔티티 쿼리 |

비브랜드 상위 15: 대전 나이트(105c·pos2) · 부산물나이트(43c·4) · 대전나이트(33c·1.5) · 일산룸(24c·7) · 청주 호박나이트(23c·3) · 일산명월관(19c·8.6) · 안산 나이트(18c·1.9) · 인계동 나이트(17c·3.8) · 일산요정(16c·9.2) · 대구 나이트 정리(15c) · 대전 나이트 추천(14c) · 대전원나이트(14c) · 전국 나이트 순위(14c·2) · 대구 바밤바(13c) · 대전 나이트클럽(12c·1.5).

2페이지(11~20위) 노출 상위 = 다음 달 1페이지 후보: 수유 샴푸나이트(226imp·11.8) · 수유샴푸나이트(205·12.5) · 인천 클럽(99·12) · 평택 호박나이트(85·11.9) · 청담 클럽(76·10.5) · 부천 고래나이트(67·10.3) · 야탑 퐁퐁나이트(64·10.3).

### D2 — 월 클릭·노출·CTR

| 지표 | 28d 현재 (07-09~08-06) | 동일방식 직전(07-03~07-31) | 방향 |
|---|---|---|---|
| GSC 웹 클릭(전수=기기합) | **1,468** (쿼리 차원 848) | 쿼리 차원 847 | 보합 |
| GSC 웹 노출(전수) | **24,519** (쿼리 차원 13,825) | 쿼리 차원 13,785 | 보합 |
| GSC 웹 CTR | **6.0%** | 6.1%(쿼리 차원) | 보합 |

⚠️ **판정 주의**: `data/growth/2026-08.json`의 `gsc_28d`(1,476클릭/27,467노출)는 monthly-full-audit 방식 — 이번 덤프 쿼리 차원(848)과 집계 방식이 다름. 9/1 판정은 반드시 **같은 방식끼리** 비교.

카테고리별 GSC 28d [직접]: /nights/ 93p·834c·18,376imp·4.54% → /magazine/ 52p·437c·**12.13%** → /region/ 67p·215c·8.37% → /yojeong/ 3p·59c·3.76% → /community/ 5p·42c·15.50% → /rooms/ 5p·41c·6.25% → /clubs/ 55p·38c·2,410imp·**1.58%** → /hoppa/ 19p·38c·6.87% → /best/ 3p·33c·10.19% → /lounges/ 4p·4c·1.92% → 홈 2c(pos 16.9).

### D3 — 정착 품질 [직접] (GA4 28d)

| 지표 | 현재값 | growth JSON 기준선(08-02) | 목표 |
|---|---|---|---|
| 세션 | 1,848 | 1,738 | — |
| 세션당 페이지 | **2.65** | 2.83 | H3: 3.1+ |
| 재방문 세션 비중 | **10.6%** (189/1,786) | returningShare 6.2%(방식 상이 ⚠️) | — |
| phone_click | **6회** (2명) | 0 (첫 계측) | H2: 30회 |
| scroll_100 | 328회 (6.7%/PV) | 6.7%/PV | 북극성② 30% |
| 한국 세션 이탈률 | **39.5%** (1,534세션) | — | 북극성③ →0 |
| 참여율(한국) | 60.5% | — | — |

참고: US발 260세션(이탈 67.3% · Flint Hill/Phoenix 등 데이터센터 도시 + Moto G Power 137세션 참여 0% 시그니처)은 봇성 — 한국 세션과 분리 해석. 재방문 체류 216초 vs 신규 90초 = 재방문 전환이 체류의 최대 레버.

---

## [4] 국내 경쟁 지형 (웹 리서치 실측 — 직접 열람 성공분만 "실측", 순위성 주장은 US geo 한계 ⚠️)

### 상위 채널 지도

| # | 채널 | 유형 | 커버 | 실측 내용 |
|---|---|---|---|---|
| 1 | 룸빵닷컴 | 업소정보+리드젠 | 룸 계열 7분류 | 업소 100+ · 강남 동단위 세분류 · "누적 후기 63,480건" 자칭(⚠️검증불가) · 연락처가 대표번호 1개로 수렴 |
| 2 | 러브보이 | 여성향 호빠 커뮤니티 | 호빠 | 게시판 4종 + **동행(친구찾기) 매칭** — 시장 유일 실측 |
| 3 | 가치놀자 | 호빠 비교 | 호빠 | 초보자용 시스템 항목화 + 안전 체크리스트 |
| 4 | 선수나라·호짱 | 구인구직(공급측) | 호빠 | 공고 1,089건·이력서 6,016건 — 업소 네트워크 장악 |
| 5 | 강남클럽닷컴·elooooo | SEO 롱폼 가이드 | 클럽·룸 | 입장 기준·예약 절차 가이드. elooooo는 "2026년 1월 기준"+폐업 목록 = 신선도 장치. 결국 마담 연락처 리드젠 수렴 |
| 6 | 다음카페 나이트클럽가이드 | 커뮤니티 | 나이트 | **회원 32,056명 실측** · 지역별 실방문 UGC 후기 연 단위 누적 |
| 7 | 나무위키 강남/클럽 | 위키 | 클럽 | 중립 포맷 신뢰. 스스로 "정보 자주 바뀜" 한계 고지 |
| 8 | Korea After Dark | 영어 블로그 | 클럽 | 표 비교+솔직 단점 병기 — 외국인 세그먼트 |
| 9 | 밤놀자류 성인 커뮤니티군 | 불법성 인접 | 룸+인접 | ⚠️403, 존재만 확인. 모방 불가 |
| +v2 | **밤픽(bampick)·nightpick** | 업소 원페이지망 | 나이트 | GEO 표본에서 "일산 나이트" 상위 실측 — quv/uriweb 빌더 위성망 |
| — | 네이버 플레이스/카카오맵 | 지도 | 전 업종 | ⚠️직접 열람 불가. "상위노출 대행" 어뷰징 정황만 |

### 실증된 불만·빈틈 (출처 있는 것만)

1. **클럽 MD 테이블 비용 불투명·배팅 부풀리기** — 언론 실증(머니투데이 2020, 한국일보·경향 2019). "정가·절차" 정보가 시장에 구조적으로 없음.
2. **"후기야 광고야" 불신** — 국민일보 실증 + 정보 사이트 다수가 대표번호 리드젠으로 수렴하는 것 직접 확인.
3. **정보 산재** — 실후기가 다음카페·코인판·네이트판 등에 흩어짐. 나무위키조차 공식 SNS로 안내.
4. **호빠 정보의 공급측 편중** — 검색 상위가 구인구직 위주. 여성 손님 관점은 러브보이·가치놀자 정도로 얇음.
5. **경쟁 기술 품질 낮음** — 호빠가이드 SSL 만료 실측, 무료빌더 서브도메인·원페이지 위성망(일산룸·명월관 검색에서 cafe24/wix 다수 실측).

### 놀쿨의 역전 후보 (콘텐츠 복제 X — 기능·UX 패턴만)

1. **"리드젠 아님" 구조를 보이는 신뢰 장치로 승격** — 실측 경쟁 전부 단일 번호 수렴. 놀쿨의 "실광고주 번호만, 없으면 빈 값"(telephone 결손 109/120이 그 증거)을 화면 노출 신뢰 장치로.
2. **신선도 표시 체계화** — 업소별 최근 확인일·영업 상태(elooooo 방식의 6업종 확장, lastmod 정직 게이트와 합치).
3. **6업종 교차 탐색** — 경쟁 전원 단일 업종 수직. "지역→6업종 한 화면"은 놀쿨만 가능(region 허브 115 기보유).
4. **초보자 시스템 해설의 업종 확장** — 부킹 절차·셀렉션 시스템 해설이 실측상 공백(절차·용어만 = 금지어 규칙과 양립).
5. **여성향 동행·후기 흐름** — 러브보이 동행 매칭이 통하는 것 실측. 모더레이션 게이트로 안전 우위 가능.
6. **검증후기 배지 노출** — rating 소스게이트를 사용자에게 보이는 검증/미검증 구분으로 — "63,480건 자칭"류의 정반대 포지션.
7. **GEO 디테일 문장 패턴 확산** — AI 요약이 실제 인용한 것은 "삼중 차음재·38세 전용" 같은 구체 팩트 문장(§2④ 실측). venue 상세엔 100% 있는 직답 구조를 매거진·region 층으로.
8. **외국인 영어 콘텐츠** — 중장기 후보 ⚠️(우선순위 보류).

---

## [5] 커버리지 — 6카테고리 × 주요 도시 매트릭스 [축적 — venues.ts·sitemap 실측]

- 총 **123업소**(전원 verified_open): 나이트 61 · 클럽 38 · 호빠 18 · 라운지 3 · 룸 2 · 요정 1.
- **"페이지만 있고 업소 0인 조합" = 0건** — prerender가 업소 ≥1일 때만 크로스 허브 생성.

| 지역 | 나이트 | 클럽 | 룸 | 요정 | 라운지 | 호빠 | 계 |
|---|---|---|---|---|---|---|---|
| 강남 | 1 | 11 | · | · | · | 3 | 15 |
| 압구정 | · | 6 | · | · | 3 | · | 9 |
| 이태원 | · | 6 | · | · | · | · | 6 |
| 일산 | 3 | 1 | 1 | 1 | · | · | 6 |
| 대전 | 4 | 1 | · | · | · | 1 | 6 |
| 홍대 | · | 4 | · | · | · | 1 | 5 |
| 광주 | 5 | · | · | · | · | · | 5 |
| 대구 | 4 | · | · | · | · | 1 | 5 |
| 부산(3권역) | 3 | · | 1 | · | · | 6 | 10 |
| 수원 | 2 | · | · | · | · | 2 | 4 |
| 청주·노원·부천 | 각2 | 각1 | · | · | · | · | 각3 |
| 청담 | 1 | 1 | · | · | · | · | 2 |
| 김포·성남·안산·천안·울산·강서·장안동·의정부·인천 | 각1~2 | 일부 | · | · | · | 일부 | 2~3 |
| 신림·수유·독산·답십리·상봉동·영등포·길동·화정·파주·구리·오산·분당·인덕원·평택·서산·구미·창원·제주 | 각1 | · | · | · | · | · | 1 |
| 건대·전주 | · | · | · | · | · | 각1 | 1 |
| 용산·용인·서울(광역) | · | 각1 | · | · | · | · | 1 |
| **합계** | **61** | **38** | **2** | **1** | **3** | **18** | **123** |

### 빈 조합 중 "실데이터 확보 가능 후보"만 (빈 페이지 양산 금지)

| 후보 | 근거(저장소 내) |
|---|---|
| **부산 × 클럽** | 부산권 10업소 인프라 + region 허브. 광역시급 중 클럽 0인 유일 초대형 시장 |
| **강남 × 룸·라운지** | 최다 15업소 지역 + 룸 전국 2곳뿐 — 확장 1순위 |
| 대구 × 클럽 / 수원 × 클럽 | 타 카테고리 2~5업소 + 허브 존재 |
| 일산 × 호빠·라운지 | 유일 4카테고리 보유 지역 |
| 압구정 × 나이트·호빠 / 홍대 × 나이트·라운지 | 클럽·라운지 인프라 + 허브 존재 |
| 대전 × 룸·라운지 / 해운대 × 클럽·라운지 | 다카테고리 인프라 + 허브 존재 |
| ⚠️ 근거 약함 | 광주·울산·제주 × 클럽, 전주 × 나이트, 요정 전 지역 — 저장소 내 교차 근거 없음 |

데이터 위생(처방 대상): 장안동 slug 이원화(jangan/jangandong) · v-051 region 충돌 잠재 · v-028 indeokvon 오타 slug(URL 고착— 변경 시 리다이렉트 필요) · 카테고리 편중 나이트+클럽 99/123(80%) = D1 호빠·라운지 미점유와 일치.

---

## [6] 가독성 — 전 663장 자동 스캔 [직접] + 대표 12곳 정밀 실측 + 기술 전수 [축적]

### 전수 자동 스캔 (dist 정적, 렌더링 없이 템플릿·CSS 기준)

**폰트 방어선**: 전역 CSS 플로어 실측 — body 16px, .text-sm→16px 승격, .text-xs류→14px 승격. **SSR 본문에 14/15px급 클래스 사용 페이지 0/663**. 잔존 구멍: `.text-[12px]`(12px)·`.text-[13px]`(13px)·`.text-[9px]` 룰이 플로어 제외로 클라이언트 렌더에서 37회 사용 + **전 663장 인라인 히어로 리드문 15px** — 정밀 실측(아래)의 14~15px 관측과 일치.

**본문 분량 (SSR 자수·문단·H2 전수)**:

| 층 | n | 자수 avg/min/max | H2 avg | 임계 미달 |
|---|---|---|---|---|
| venue 상세 nights | 61 | 2,377/1,724/7,087 | 15 | <1700자 **0** |
| venue 상세 clubs | 38 | 1,964/1,446/6,098 | 14 | <1700자 **18곳**(1,446~1,679 — 유일 미달군, 전체 목록 원시 JSON) |
| venue 상세 hoppa/rooms/lounges/yojeong | 24 | 2,127~2,955 | 15~21 | 0 |
| magazine 글 | 59 | 2,105/1,174/8,490 | 10 | — |
| **집계형 tag·region·near·new/best** | 386 | **813~1,215** | 9~10 | 리스팅 <2000자 **386/386** (단 tag 172는 noindex) |
| title >60자 / desc >150자 / desc 없음 | 663 | — | — | **0 / 0 / 0** · desc <80자 234(색인 대상 실질 = near 37 + region 3) |
| H2 <5 페이지 | 663 | — | — | **0** (사이트 최소 8개) |

### 대표 12곳 정밀 실측 (라이브 390×844 헤드리스 · 클릭 0 · webdriver 차단 = GA 오염 0) [v1 실측 유지]

| # | 페이지 | 본문 px | line-height | 대비비 | 평균/최대 문단 자수 | 44px 미달 | 특이 |
|---|---|---|---|---|---|---|---|
| 1 | 홈 / | 16 | 1.7 | 6.84 | 124/244 | 0 | 14px 미리보기 문단 12개 |
| 2 | /nights/ | 16 | 1.7 | 14.98 | 110/225 | 0 | sticky 필터 무해 |
| 3 | /clubs/ | **14** | 1.7 | 15.91 | 105/183 | 0 | 16px 규칙 미달 |
| 4 | /rooms/ | 16 | 1.7 | 14.98 | 129/215 | 0 | 양호 |
| 5 | 나이트 상세(청담H2O) | 16 | 1.7 | 14.59 | 115/250 | 0 | 양호 |
| 6 | 클럽 상세(레이스) | **14** | 1.7 | **6.84** | 111/183 | 0 | 14px+회색 — 최하 |
| 7 | 룸 상세(일산룸) | 16 | 1.7 | 14.59 | 110/223 | 1 | 링크 24px 1건 |
| 8 | 호빠 상세(깐따삐야) | 16 | 1.7 | 14.59 | 118/248 | 0 | 양호 |
| 9 | 요정 상세(명월관) | 16 | 1.7 | 14.98 | 116/199 | 1 | 링크 24px 1건 |
| 10a | /magazine/ 허브 | **14** | 1.7 | 7.46 | 128/202 | 0 | 14px 회색 발췌 58개 |
| 10b | 매거진 글(강남 EDM) | 16 | 1.75 | 11.59 | 140/269 | **7** | 내부링크 24px 7건 |
| 11 | /community/free/ | 16 | 1.7 | 7.10 | 123/124 | 0 | 목록형 정상 |
| 12 | /guide/ilsan-yojeong/ | **15** | 1.7 | 14.59 | 114/148 | **3** | 15px 본문+21px 링크 |

공통: H1 28px 통일 · 하단 고정 nav 57px vs padding 72px = 가림 0 · 가로 스크롤 0 · 대비 전 페이지 WCAG AA 통과.
**리스크 상위 5**: ①클럽 라인 14px(허브+상세, 상세는 대비 6.84 최악 조합) ②가이드 15px+21px 링크 ③매거진 허브 14px 발췌 58개 ④매거진 내부링크 24px 7건 ⑤홈·커뮤니티 대비 6.8~7.1.

### 기술 전수 (풀크롤 축적분 재사용 — 전부 관측 2026-08-08)

| 축 | 전수 | 결과 | 런 |
|---|---|---|---|
| 죽은 링크·이미지(라이브) | 472p 크롤 → 820 URL 검증 | **broken 0** | deep-audit 31234980026 |
| 내부 링크(dist 정적 663장) | 고유 href 812 | **죽은 링크 0** (구 URL 39개는 전부 _redirects 301 커버) | [직접] |
| 라이브 HTTP 상태 | sitemap 472 전수 | **200 OK 472 · 4xx/5xx 0** | sunday-deep-audit 31271951100 |
| 콘솔·JS·네트워크 에러 | 50 URL × 11 뷰포트 = 550로드 (⚠️472 전수 아님 — limit 50) | **이슈 0** (CONSOLE/JS/NET/OVERFLOW/FONT/TOUCH 전부 0) | nightly-full-audit 31273613591 |
| SEO 7축 | 472 전수 | 회귀 0 | seo-deep-audit-watch 31238781367 |
| venue 상세 SEO 12지표 | 123 전수 | **123/123 만점** | sunday-deep-audit |
| freshness | — | ⚠️7: magazine stale 6편(149~161일 — gangnam-edm-clubs-2026 등) + sitemap lastmod 당일 미갱신 | deep-audit |

---

## [7] 무인화 준비도 [직접 API + 저장소 실측, 08-08 기준]

### 인벤토리 (총 163 워크플로)

| 분류 | 개수 | 대표 |
|---|---|---|
| venue keyword-watch (24h) | 79 | KST 07:00~14:05 5분 간격 분산 |
| 일일 | 51 | northstar 08:20 · ga-health 08:00 · 회귀 다이제스트 09:00 · lighthouse 04:00 · clarity-watch 21:00 · backup 03:00 |
| 주간 | 11 | 월요일 집중(색인·SC리포트·순위추이·SERP 루프) + 일 03:00 딥오딧 |
| 월간 | 2 | monthly-full-audit(30일 200축) · billing |
| dispatch 전용 | 18 | GA4 관리/진단 10 + Places 2 + 온디맨드 6 |
| 기타 | 2 | audit-pr(PR) · migrate(push) |

schedule 보유 144/163(88%) · audit-pr 제외 전부 수동 재실행 겸용.

### 최근 성공률 [⚠️커버리지: 08-06 17:39~08-08 20:47 UTC 최신 500런]

- **성공 491 / 실패 7 / 성공률 98.6%** · 관측 132종 · **지속 실패 0개**. 실패 7건 = 08-07 새벽 한 구간 클러스터(일시 장애, 전부 자동 회복). +v2 실측: 08-08 색인검사 job 1건 타임아웃 취소(50분 상한) — 색인 전수는 주간 google-index-coverage가 커버 중이라 실해 0.

### 사람 손이 아직 필요한 지점 (전수)

| 유형 | 내용 |
|---|---|
| ① 사장님 콘솔 1회 액션 | GA4 서비스계정 "편집자" 승격(평시 뷰어 403 보고만) — ga4-admin-apply·em-scroll-off 대기 · Clarity consentv2 |
| ② 의도적 사람 주도 | 월간 성장 사이클 레버+마감(매달 1일) · seo-weakness 다이제스트 검토 |
| ③ 성격상 무인화 불가 | 광고주 요청 콘텐츠(전화바·썸네일 합성·백링크) — 최근 100커밋 중 수동 37건의 주 패턴 |
| ④ 자동감시→사람 수정 | watch 적발 회귀의 근본수정(예: 08-02 지메일 3계통) |
| 선택 갭 | 텔레그램 미연결(이메일 폴백 실해 0) · Places 채움 dispatch 전용 대기 |
| 자기보류(사람 불요) | 스크립트 "보류" 14곳 전부 데이터 임계 자기수렴형 |

⚠️ 미확인: 08-01~06 초반 런 성공률(API 페이지 한도) · Clarity consentv2 완결 여부.

---

## [8] 9/1 판정 준비 — H1·H2·H3 현재 중간 스냅샷 (2026-08-08)

⚠️ 공통: 28d 창의 절반 이상이 처방 적용(08-02) 이전 — 중간값은 추세 참고용, 확정 판정은 9/1의 28d 창으로.

| 가설 | 기준선(JSON 08-02) | **현재 중간값** | 목표 | 방향 |
|---|---|---|---|---|
| H1a. 6곳 합산 CTR | 0.66% (31c/4,702imp) | **0.87%** (29c/3,343imp) · 동일방식 08-02 대조 0.69% | 2.0%+ | ↗ 상승 중, 거리 큼 |
| H1b. nights 카테고리 CTR | 3.93%(⚠️방식 상이) | **4.54%** · 동일방식 대조 4.73% | 4.5%+ | 동일방식 기준 소폭 ↘ |
| H2. phone_click 28d | 0 (첫 계측) | **6회**(2명·실질 ~6일치) | ≥30회 | 일평균 ~1회 → 28d 환산 ≈28회, 경계선 |
| H3a. 세션당 페이지 | 2.83 | **2.65** | 3.1+ | ↘ 주의 |
| H3b. 고이탈 4곳 평균 이탈 | 58.8% | **52.9%** (-5.9pp) | -5pp | ✅ 궤도 위 |

H1a 6곳: 청주슈퍼문 9c/449imp(2.0%·6.7) · 대전세븐 6c/869(0.7%·8.3) · 답십리 5c/361(1.4%·9.1) · 이태원유토피아 4c/407(1.0%·9.0) · 일산샴푸 3c/592(0.5%·9.9) · 수유샴푸 2c/665(0.3%·11.5 유일 2페이지).
H3b 4곳: 줄리아나 74.3→**84.4% 악화** · 평택호박 58.1→53.6 · 광주region 52.9→**33.3 대폭 개선** · 강서호박 50.0→40.4. 평균은 궤도 위, 줄리아나 단독 악화가 리스크.
H2 페이지 분해(대전원나이트·일산룸·명월관 축)는 이벤트×페이지 차원 미덤프 ⚠️ — 9/1 판정 시 분해 필요. +v2 행동 근거: Clarity 3일 rage/dead 집중 URL이 대전세븐·대전가이드(H1a/CTR 미달 목록과 동일 페이지) — "노출은 받는데 눌리지 않고, 들어와서도 클릭이 헛도는" 페이지가 일치함.

**판정 오염 방지 재확인**: v2 추가 조사는 런로그 GET·dist 정적 스캔·WebSearch뿐 — 지표 개입 변경 0.

---

## 부록 — 데이터 정합성 메모 (9/1 판정·처방 발행 시 필독)

1. **GSC 전수 vs 쿼리 차원 격차 42%**: 기기 차원 합(1,468c/24,519imp)이 진짜 전수, 쿼리 차원 합(848/13,825)은 익명화 제외분 — 계열·판정마다 어느 쪽인지 명시할 것. growth JSON(1,476/27,467)은 제3의 방식(monthly-full-audit).
2. **GA4 사이트 단일 합계 호출 HTTP 400** — ga4-full-dump.mjs ⑧구간 실패로 engagedSessions 등 합계 지표 누락(차원별 값으로 대체 가능, 스크립트 수정은 처방에서).
3. **봇 시그니처**: Moto G Power(2022) 137세션 + Android 11.0 137세션 = 참여 0%·체류 0초 완전 일치 · US 데이터센터 도시 260세션 · 새벽 4시대 130세션(참여 27.7%) — 한국 실사용자와 분리 해석.
4. **슬래시 이중 집계**: GA4 pagePath /nights vs /nights/ 광범위 + GSC 무슬래시 /nights/daejeononenight 노출 882(순위 2.8) 별도 노출 — canonical/301 정리 여지(처방 대상).
5. **잔존 흔적**: "site:pages.dev" 노출 2회(구 도메인 잔존 색인) · "쿨입장.com" 노출 29회·클릭 0.
6. **색인검사 job 이중화 주의**: ga4-gsc-full-dump의 --only-index job은 472 URL × ~2s가 50분 상한에 걸려 취소됨(08-08 실측) — 색인 전수는 주간 google-index-coverage(최근 08-03: 444/472) 쪽을 소스로 쓸 것.
7. GA4 08-08 당일 행(참여율 9.8%)은 집계 미완 왜곡 — 판정 미사용.
8. Clarity 스크롤 깊이 62.8→45.5% 3일 하락은 실세션 29→48 증가(구글 모바일 얕은 유입 확대)와 동반 — 절대 악화가 아니라 유입 구성 변화로 읽을 것.

*작성: Claude (파트1/5 검사 기사 · v2 확장 2026-08-09) · 코드/콘텐츠/설정 수정 0 · 커밋 1회(이 파일). 원시 데이터: GH 런 31277666498(GA4/GSC) · 31274742570(Lighthouse) · 31107324007/31179308010/31257336366(Clarity) · 30780379637(색인) · dist 스캔 스크립트=세션 스크래치패드.*

---

# 파트2/5 처방 이행 내역 (2026-08-09 · 커밋 `eaa91cd4`)

> 파트1 보고서(위)의 실측을 근거로 처방 파트2를 이행한 결과. **게이트 전체 PASS(빌드 exit 0)** → push 1회 → 라이브 반영·직접 렌더 검증 완료. 표기: ✅ 라이브 검증 완료 · ⚠️ 부분/보류(사유 병기) · ❌ 미이행. 개입 범위는 `data/growth/2026-08.json` `part2_intervention`에 기록.

## A~H 정직 결과표

| # | 근거(파트1 수치) | 수정 | 라이브 검증 | 판정 |
|---|---|---|---|---|
| A1 | /nights/daejeononenight 무슬래시 882노출·CTR 0.7%·순위 2.8 | 무슬래시→슬래시 리다이렉트·canonical 정합 확인 + 상세 title·shortDesc 직답형 재작성 | 무슬래시 = **308 영구 리다이렉트→/…/** · 슬래시 canonical=자기 자신(정합) · 새 title 라이브 | ✅ |
| A2 | "대전 클럽" 102노출·CTR 0%·순위5.0 · "청주 클럽" 162·0.6%·5.2 | /clubs/대전·/clubs/청주 SSR+client 직답 카피(월평동 대전설탕클럽·성안길 슈퍼문). **팩트교정 '둔산동'→'월평동'** | 두 허브 새 title 라이브 확인 | ✅ |
| A3 | CTR 미달 페이지10·쿼리9(H1a 6곳 제외) | 나머지 8곳 title/desc 재작성(아래 CTR 표) | 8곳 dist·라이브 반영 · title 게이트 위반 0 | ✅ |
| A4 | 대전세븐 dead 37이벤트·rage 30이벤트 / 대전가이드 rage 27 | tel 복사 폴백·매거진 본문 내부링크 SPA 라우팅·마일스톤 토스트 클릭차단 해제·퀴즈 재선택·완독카드 탭공개·features 칩 버튼외형 제거·ShareButtons 폴백 | 대전세븐 tel 2개 렌더·번호 노출 · 매거진 링크 클릭=**SPA 클라이언트 라우팅**(full-reload 아님, probe 생존) · 콘솔 에러 0 | ✅ |
| B | /clubs 랜딩 참여율 4.3% | 첫 화면 직답 블록("지금 볼 수 있는 클럽 N곳")+지역 1클릭 칩 | 직답 블록 렌더 확인 · 콘솔 0 | ✅ |
| C | 홈 quickback 3일 연속 | 첫 뷰 인기 TOP(/ranking) 1클릭 칩 | /ranking 칩 렌더 확인 · 콘솔 0 | ✅ |
| D | perf 70·모바일 LCP 5.2~7.5s(7페이지) | 기존 시즌29-F preload(venue hero webp·fetchpriority=high) 인프라 확인·유지 + E 폰트 최적화. 웹폰트 없음=display:swap N/A. gtag async·Clarity 비동기 확인 | 코드 확인 완료. **허브 페이지 LCP 요소 preload는 레이아웃 동결 원칙상 신규 개입 보류** → 파트3 이월 | ⚠️ |
| E | 히어로 리드 15px·클라이언트 12/13px 37회·터치 44px 미달 12건 | 15→16px·12/13px→14px 플로어 승격·rich-content 링크 44px·가이드 목차 36→44px | 빌드 메타-게이트 PASS(457장 폰트/터치 전수) | ✅ |
| F | 색인 444/472(미색인 28) | noindex 5곳 + canonical 쌍둥이 통합 10곳 → sitemap 제외 | **sitemap 472→457** · noindex 페이지 robots=noindex·sitemap 제외 확인 · /region/일산/clubs canonical→/clubs/ilsan/ 확인 | ✅ |
| G | 매거진 stale 6편(149~161일) | gangnam-edm-clubs-2026 운영정보 실데이터 갱신 + "2026년 8월에 다시 확인" 표기. 갱신 근거 없는 5편 무변경 | "2026년 8월에 다시 확인" 라이브 노출 확인 | ✅ |
| H | 04시 봇대 참여 27.7% / 사장님 콘솔 1회 | 소스·패턴 특정(아래) + 콘솔 필요 항목은 클릭 안내 블록으로 | GA4 필터·consent v2는 콘솔 권한 필요 → 사장님 액션 안내 | ⚠️(안내) |

**총 PASS 9 ✅ · 보류/안내 2 ⚠️ · 미이행 0 ❌** (A1·A2·A3·A4·B·C·E·F·G = ✅ / D·H = ⚠️).

## A CTR 재작성 표 (쿼리·노출·현재 CTR → 새 title)

| 페이지/쿼리 | 노출 | 현재 CTR | 새 title |
|---|---|---|---|
| /nights/daejeononenight (무슬래시) | 882 | 0.7% | 대전원나이트 — 38세부터만 문 열어주는 중앙로역 5분 홀, 금·토 새벽 3:30까지 돈다 |
| /nights/busanasiadnight/ · "온천장 아시아드 나이트" | 508 / 225 | 0.6% / 0% | 부산아시아드나이트 — 온천장역 5분 발코니에서 내려다보면 토요일 플로어가 왜 차는지 안다 |
| /nights/suwonchancenight/ | 309 | 0% | 수원찬스돔나이트 — 벚꽃이 천장으로 흐르는 인계동 360도 돔, 안 본 사람은 모른다 |
| /nights/sangbonghangukgwannight/ | 240 | 0% | 상봉동한국관나이트 — 망우로 2층 계단 끝 색소폰 30분, 중랑·구리 단골이 몰린다 |
| /near/신사/ | 176 | 0% | 신사역 걸어서 5분, 오늘 갈 곳 — 위치·후기·전화번호 거리순으로 바로 정리 (스터핑 회피 위해 업소명 미노출) |
| /magazine/gangnam-octagon-guide/ | 350 | 0.6% | 강남클럽 옥타곤 — 학동역 4번 출구 지하 입구부터 라인업 읽는 법까지, 처음 가도 안 헤맨다 |
| /clubs/대전 · "대전 클럽" | 102 | 0% | 월평동 대전설탕클럽 — 미러볼 12개 도는 지하, 이태원 출신 DJ가 새벽까지 끌어올린다 |
| /clubs/청주 · "청주 클럽" | 162 | 0.6% | 성안길 청주클럽 슈퍼문 — 드롭 순간 직경 2미터 미러볼이 홀을 뒤덮는다 |

*H1a 6곳(청주슈퍼문·대전세븐·답십리·이태원유토피아·일산샴푸·수유샴푸)은 title 무개입(9/1 판정 보호). 줄리아나(84.4%) 무개입 유지. 모든 새 카피는 venue 실데이터 검증(미러볼 12개/발코니 관람석/벚꽃 프로젝션/색소폰 계단 = 원본 description 확인).*

## LCP 전/후 표 (모바일 lab · Slow 4G)

| 페이지 | 전(08-09 04:34 런) | 후 | 비고 |
|---|---|---|---|
| / | 7.47s (perf 69) | ⚠️ 미측정 | 이번 파트 render-chain 신규 개입 0 → lab 변동 없음 예상 |
| /clubs/ | 5.85s (74) | ⚠️ 미측정 | B 직답 블록은 SSR 텍스트(이미지 추가 0) |
| /nights/ | 6.42s (70) | ⚠️ 미측정 | — |
| /lounges/ | 7.20s (70) | ⚠️ 미측정 | — |
| /community/ | 6.10s (72) | ⚠️ 미측정 | — |
| /magazine/ | 5.22s (68) | ⚠️ 미측정 | — |
| /rooms/ | 6.89s (70) | ⚠️ 미측정 | — |

**정직 고지**: D는 허브 페이지 render-chain에 **신규 코드 개입을 하지 않았다**(레이아웃 동결·사이트 피해 0 원칙). 따라서 lab LCP는 유의미하게 변하지 않을 것으로 예상되며, 즉시 로컬 Lighthouse 재측정 대신 **내일 04:00 lighthouse-daily 자동 런**을 기준 후측정으로 삼는다. 허브 LCP 요소 특정→preload는 **파트3**에서 페이지별로 안전하게 처리한다.

## H 진단 + 사장님 콘솔 클릭 안내 블록

**H① 04시 봇대(참여 27.7%) 소스·패턴 특정**: 파트1 부록3 실측과 일치 — 04시대 130세션은 **Moto G Power(2022) 137세션 + Android 11.0 137세션(참여 0%·체류 0초 완전 일치) + US 데이터센터 도시(Flint Hill/Phoenix 등) 260세션** 봇 시그니처가 새벽 시간대에 집중된 것. 코드/콘텐츠로는 막을 수 없고 GA4 데이터 필터(내부/봇 트래픽 제외) = **콘솔 권한 필요**. 추측 설정 금지 원칙에 따라 아래 클릭 안내로 대체.

**사장님이 직접 1회만 눌러주실 것 (클릭 단위):**
1. **GA4 서비스계정 "편집자" 승격** — analytics.google.com → 관리(왼쪽 아래 톱니) → 계정/속성 열의 "속성 액세스 관리" → 우상단 파랑 `+` → "사용자 추가" → 서비스계정 이메일 입력 → 역할 "편집자" 체크 → 저장. (현재 뷰어 권한이라 ga4-admin-apply·em-scroll-off 워크플로가 403 보고만 함)
2. **GA4 봇/새벽 트래픽 필터** — 관리 → 데이터 설정 → 데이터 필터 → "내부 트래픽" 활성 + (편집자 승격 후) 데이터 스트림 → 태그 설정 더보기 → "알려진 봇·스파이더 제외" 켜짐 확인. Moto G Power/데이터센터 IP는 별도 세그먼트로 리포트에서 제외 해석(이미 파트1이 분리 해석 중).
3. **Clarity consent v2 완결** — clarity.microsoft.com → 프로젝트 xp3oiz8heq → Settings → Setup → Cookie consent → "v2" 안내에 따라 동의 배너 연동 상태 확인/저장.

*이 3건은 콘솔 권한이 필요해 이 터미널에서 실행 불가(사이트 피해 0·추측 설정 금지). 완료되면 관련 워치가 자동으로 403→정상 전환됨.*

## 배포·회귀 검증 요약

- 13 주요 경로 전부 **200 OK** (홈·6카테고리·community·clubs/대전·clubs/청주·near/신사·guide/ilsan-yojeong).
- 하단 전화바 정상: 대전세븐 `tel:01032421504` 2개 렌더 + 담당자 문구 · 일산요정 가이드 `tel:01036954929` 렌더.
- 썸네일 v2 / OG: 커밋이 이미지·og 로직 미변경(git 확인) → 해시 무손상 · 라이브 webp 200.
- 금지 표현 0(빌드 가드 PASS) · 대전원나이트 "차비 3만원"은 문서화된 단일 예외 · 매거진 "2차·3차"는 호핑 코스 문맥(가드 통과).
- 수정 페이지 전수 **콘솔 에러 0**(대전세븐·/clubs·홈·매거진·가이드 렌더 검증).
- 게이트: tsc 0 · 빌드 exit 0(lastmod 정직·밀도·스터핑·체류·title차별화·집계허브 단어중복0·메타 전수·GA4 태그 전부 PASS).

*작성: Claude (파트2/5 처방 기사 · 2026-08-09) · 커밋 `eaa91cd4`(코드+본 보고서 append). 개입 로그: `data/growth/2026-08.json` part2_intervention.*

---

# 파트2.5/5 긴급 정직화 — 가짜 UGC 전면 제거 (2026-08-09 · 커밋 c36f3616·8c46c347·5e85dfc7)

> 배경: 홈 "최근 올라온 글/지금 뜨는 이야기/밤의 온도"에 가짜 회원 글(가짜 좋아요·불꽃지표)이 **15분마다 자동 생성기로 주입**되고 있었다(라이브 실측). 사이트 #1 규칙 "가짜 0" 위반 + 표시광고법(기만적 후기·활동 조작) 리스크. 원칙: **비어 있는 정직 > 가득 찬 가짜.** 파트2가 수술한 홈 첫 화면(직답·지역·인기TOP)은 보존, 커뮤니티 영역만 손댔다.

## A~D 정직 결과표

| # | 문제(실측) | 조치 | 라이브 검증 | 판정 |
|---|---|---|---|---|
| A1 | 자동 생성기(auto-content-v2)가 15분마다 가짜 글·댓글·좋아요 주입 | schedule(*/15) 제거 + 스크립트 하드가드(즉시 exit) + no-fake-seed 게이트 확장(재활성화 시 빌드 차단) | 생성기 워크플로 disabled · 게이트 PASS | ✅ |
| A1 | DB에 가짜 글 1544·댓글 2142 | 3-pass 마이그레이션(백업 후 삭제, push 자동실행·전부 success) | **posts 1544→16 · comments 2142→0 · reviews 0**(MCP 실측) | ✅ |
| A1 | "후기" 태그 가짜 글 | reviews 카테고리 시드글(user_id NULL) 삭제 | 라이브 커뮤니티 가짜 후기 0 | ✅ |
| A2 | 정보성 가짜 글 소재 폐기·운영팀 공식글 후보 | 이번엔 작성 0, 후보 목록만 기록(파트3 게이트 통과 후 발행) | growth JSON part3_operator_content_candidates | ✅ |
| A3 | 동일 글 중복 노출 버그 | FreshPostsZone의 '최근글 fallback'(HomeFeed와 중복+가짜 신선도) 제거 → 진짜 30분내만 | 홈 중복 0(가짜 피드 자체가 은닉) | ✅ |
| B | 홈 "최근글/뜨는이야기/밤의온도 TOP5(데이터없음)" 가짜 노출 | useCommunityActive 자동스위치(7일 실글 ≥5 복귀/미만 은닉, 상수) 뒤로 이동. 미활성 시 정직 시작카드 | posts_last_7d=0 → **가짜 피드·온도 은닉·정직카드 노출**(실측) · 콘솔0 | ✅ |
| B | 연속출석 위젯 비로그인 노출 | StreakBadge 로그인 회원 전용 | 비로그인 홈에서 제거 확인 | ✅ |
| B | OPEN BETA "방금 오픈"·창립멤버 자리수 | "커뮤니티 시작 단계"로 정직화 · 자리수는 user_profiles 실측(가짜 유저 삭제 후 실수치) | 배너 정직 노출 | ✅ |
| B | 커뮤니티 페이지 정직 배너 | /community 상단 "지금 커뮤니티를 시작하는 중"(과장0) | 배너 노출·가짜 0(실측) | ✅ |
| C | 운영자↔회원 오인 | AuthorBadge(🛡️운영팀 공식 명찰) 글·댓글 작성자 옆 + 사칭 예약닉네임 가입/프로필 차단 | 명찰 구조 구현·빌드 PASS | ✅ |
| C | 창립멤버 뱃지 부여 로직 | useFoundingMember(가입 순번 joined_at≤100) 존재 확인 | 로직 존재 | ✅ |
| C | 가입→글쓰기 동선·신고 버튼 | 로그인 게이트까지 왕복 정상(write→login 리다이렉트·폼 렌더·콘솔0) · ReportButton 존재 | 라이브 정상 | ✅(인증 게이트까지) |
| D | 회귀 | 13경로 200(커뮤니티/로그인은 308→200 슬래시정합) · 파트2 전화바·썸네일 무손상 · 수정페이지 콘솔0 | 실측 통과 | ✅ |

**총 PASS 13 ✅ · ❌ 0.**

## 가짜 vs 진짜 식별 — provably-safe (실글 삭제 0 근거)

3-pass로 나눈 이유 = 가짜가 두 경로로 유입됐고 각각 다른 안전 서명이 필요했다:
1. **1차** `user_id IS NULL`(SQL 시드 v1~v5) + seed_authors 닉네임 → **757 삭제**. (실글은 createPost가 user_id=사용자.id 저장, NULL 불가)
2. **2차** 활성 생성기(auto-content-v2)는 **실계정 19인 명의**로 써서 작성자 구분 불가 → 생성기 불변 서명 **`likes >= 2`**(생성기는 삽입 시 rand(≥2) 주입, 실글은 항상 0~1). 실측: likes≥2=771(가짜)·likes<2=16(광고주 아톰 홍보·실유저 글, 전부 likes 0) → **771 삭제, 16 보존**.
3. **3차** 남은 59댓글 = **seed_comment_pool 240문구 본문 대조** → 56 일치(생성기)+고아 3 삭제, 실댓글은 고유 본문이라 보존 로직(단 실댓글 3개는 삭제된 가짜 글에 달린 고아라 함께 제거됨).

→ 테스트계정(유저A=사장님/유저B)·광고주 계정·실유저 계정과 그들의 실제 글 16개는 **삭제 0**. 원본은 backup/fake-ugc-원본/(시드 소스) + DB `_fake_ugc_backup_20260809_*`(생성기 실행분 포함, 복구 가능)에 이중 보존.

## 사장님 참고(선택)

- 현재 커뮤니티는 실글 16개(대부분 광고주 홍보 반복글)뿐. 홈은 자동으로 커뮤니티를 숨기고 정직 시작카드를 노출 중. 실회원 글이 7일 5건 이상 쌓이면 커뮤니티 섹션이 자동 복귀.
- 남은 auth.users 고아 계정(프로필 삭제된 가짜 seed_authors)은 무해(로그인·노출 불가). 완전 정리를 원하면 콘솔에서 삭제 가능(선택).
- 파트3에서 "놀쿨 운영팀" 명찰로 양주/드레스코드/부킹 공식 가이드 발행 예정(회원 글 사칭 아님, 게이트 통과분만).

*작성: Claude (파트2.5/5 정직화 기사 · 2026-08-09) · 커밋 c36f3616(코드)·8c46c347·5e85dfc7(DB 마이그레이션)·본 append.*
