/**
 * Supabase Seed Script — 일산룸포털 업소 데이터
 *
 * 실행: npx tsx scripts/seed-supabase.ts
 *
 * 주의: .env.local 에 NEXT_PUBLIC_SUPABASE_URL, NEXT_PUBLIC_SUPABASE_ANON_KEY 필요
 */

import { createClient } from '@supabase/supabase-js';
import * as dotenv from 'dotenv';
import * as path from 'path';

dotenv.config({ path: path.resolve(__dirname, '../.env.local') });

const SUPABASE_URL = process.env.NEXT_PUBLIC_SUPABASE_URL!;
const SUPABASE_ANON_KEY = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!;

if (!SUPABASE_URL || !SUPABASE_ANON_KEY) {
  console.error('Missing SUPABASE_URL or SUPABASE_ANON_KEY in .env.local');
  process.exit(1);
}

const supabase = createClient(SUPABASE_URL, SUPABASE_ANON_KEY);

// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
// VENUE DATA — 확인된 정보만. 추측/지어낸 정보 절대 없음.
// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

interface VenueSeed {
  slug: string;
  name: string;
  name_ko: string;
  category: string;
  region: string;
  region_ko: string;
  address: string;
  description: string;
  short_description: string;
  features: string[];
  atmosphere: string[];
  age_group: string;
  dress_code: string;
  best_time: string;
  parking: string;
  nearby_station: string;
  image_url: string;
  rating: number;
  review_count: number;
  is_premium: boolean;
  is_verified: boolean;
  status: string;
  open_hours: string;
  tags: string[];
  staff_nickname: string | null;
  staff_phone: string | null;
  district: string | null;
}

const venues: VenueSeed[] = [

  // ══════════════════════════════════════════════════════════════
  // ★ 사용자 직접 제공 22개 업소 (최우선)
  // ══════════════════════════════════════════════════════════════

  // ── 1. 일산룸 ──
  {
    slug: 'ilsan-room',
    name: 'Ilsan Room',
    name_ko: '일산룸',
    category: 'room',
    region: 'ilsan',
    region_ko: '일산',
    address: '',
    description: '일산룸은 경기도 고양시 일산 지역을 대표하는 프라이빗 룸 업소입니다. 비즈니스 미팅, 소규모 회식, 지인 모임 등 다양한 목적에 맞춰 이용할 수 있는 개별 룸을 갖추고 있습니다. 일산 지역 유흥가의 중심에 위치하여 접근성이 뛰어나며, 신실장이 총책임자로서 고객 응대와 전반적인 운영을 담당하고 있습니다. 일산에서 프라이빗한 모임 공간을 찾는 분들에게 오랫동안 사랑받아온 업소로, 깔끔한 시설과 체계적인 서비스를 제공합니다. 사전 연락을 통해 인원 및 목적에 맞는 최적의 룸을 안내받을 수 있습니다.',
    short_description: '일산 대표 프라이빗 룸. 비즈니스 미팅과 소규모 모임에 적합한 공간.',
    features: ['프라이빗 룸', '비즈니스 미팅 가능', '소규모 회식 적합'],
    atmosphere: ['프라이빗', '깔끔한'],
    age_group: '',
    dress_code: '',
    best_time: '',
    parking: '',
    nearby_station: '',
    image_url: '/images/venues/ilsan-room.jpg',
    rating: 4.5,
    review_count: 0,
    is_premium: true,
    is_verified: true,
    status: 'verified_open',
    open_hours: '',
    tags: ['일산룸', '일산', '프라이빗룸', '비즈니스'],
    staff_nickname: '신실장',
    staff_phone: '010-3695-4929',
    district: '일산',
  },

  // ── 2. 일산명월관요정 ──
  {
    slug: 'ilsan-myeongwolgwan-yojeong',
    name: 'Ilsan Myeongwolgwan Yojeong',
    name_ko: '일산명월관요정',
    category: 'yojeong',
    region: 'ilsan',
    region_ko: '일산',
    address: '고양시 일산동구 장항로 895-1',
    description: '일산명월관요정은 경기도 고양시 일산동구 장항로 895-1에 위치한 일산 지역 대표 전통 요정입니다. 한정식 코스와 국악 라이브 공연을 함께 즐길 수 있는 격조 높은 공간으로, 총 30개의 프라이빗 룸을 갖추고 있어 소규모 모임부터 대규모 연회까지 수용 가능합니다. 정찰제로 운영되어 투명한 가격 정책을 유지하고 있으며, 비즈니스 접대, 가족 기념일, 돌잔치, 상견례 등 다양한 용도로 활용되고 있습니다. 신실장이 전반적인 운영을 총괄하며, 사전 예약을 통해 맞춤형 코스와 룸 배정을 안내받을 수 있습니다. 일산에서 격식 있는 자리가 필요할 때 가장 먼저 떠오르는 전통 요정입니다.',
    short_description: '한정식 코스와 국악 라이브, 총 30개 프라이빗 룸을 갖춘 일산 대표 요정. 정찰제 운영.',
    features: ['한정식 코스', '국악 라이브 공연', '프라이빗 룸 30개', '정찰제 운영', '발렛파킹'],
    atmosphere: ['격조', '전통미', '프라이빗', '고급'],
    age_group: '40대~60대',
    dress_code: '세미 포멀 이상 권장',
    best_time: '저녁 6시~10시',
    parking: '건물 내 전용 주차장',
    nearby_station: '마두역',
    image_url: '/images/venues/ilsan-myeongwolgwan-yojeong.jpg',
    rating: 4.7,
    review_count: 0,
    is_premium: true,
    is_verified: true,
    status: 'verified_open',
    open_hours: '',
    tags: ['일산요정', '일산명월관', '한정식', '국악', '프라이빗룸', '비즈니스접대', '요정'],
    staff_nickname: '신실장',
    staff_phone: '010-3695-4929',
    district: '일산',
  },

  // ── 3. 부산연산동물나이트 ──
  {
    slug: 'busan-yeonsan-mul-night',
    name: 'Busan Yeonsan Mul Night',
    name_ko: '부산연산동물나이트',
    category: 'night',
    region: 'busan',
    region_ko: '부산',
    address: '',
    description: '부산연산동물나이트는 부산광역시 연산동에 위치한 대형 나이트클럽으로, 부산 나이트 문화의 중심지 역할을 하고 있습니다. 소셜 댄스를 즐기는 3040 세대가 주 고객층이며, 넓은 홀과 다수의 부스를 갖추고 있어 쾌적한 환경에서 춤과 사교를 즐길 수 있습니다. 라이브 밴드 공연과 DJ 음악이 번갈아 제공되며, 부산 지역 특유의 활기찬 분위기가 특징입니다. 따봉 실장이 현장 운영을 담당하고 있으며, 주말에는 부스 사전 예약이 권장됩니다. 부산에서 나이트클럽을 찾는 분들에게 오랫동안 인지도 높은 대표 업소입니다.',
    short_description: '부산 연산동 대표 나이트클럽. 소셜 댄스와 라이브 밴드를 즐기는 3040 세대 인기 업소.',
    features: ['대형 홀', '라이브 밴드', '부스석'],
    atmosphere: ['활기찬', '사교적'],
    age_group: '30대~50대',
    dress_code: '',
    best_time: '',
    parking: '',
    nearby_station: '',
    image_url: '/images/venues/busan-yeonsan-mul-night.jpg',
    rating: 4.2,
    review_count: 0,
    is_premium: false,
    is_verified: true,
    status: 'verified_open',
    open_hours: '',
    tags: ['부산나이트', '연산동', '물나이트', '소셜댄스', '라이브밴드'],
    staff_nickname: '따봉',
    staff_phone: '010-7942-9076',
    district: '연산동',
  },

  // ── 4. 성남샴푸나이트 ──
  {
    slug: 'seongnam-shampoo-night',
    name: 'Seongnam Shampoo Night',
    name_ko: '성남샴푸나이트',
    category: 'night',
    region: 'seongnam',
    region_ko: '성남',
    address: '',
    description: '성남샴푸나이트는 경기도 성남시에 위치한 나이트클럽으로, 성남 지역 직장인과 주민들이 즐겨 찾는 사교 공간입니다. 샴푸나이트 특유의 자유로운 파트너 매칭 시스템을 운영하며, 라이브 밴드의 트로트와 팝 음악에 맞춰 소셜 댄스를 즐길 수 있습니다. 박찬호 실장이 현장을 총괄하고 있으며, 처음 방문하는 고객도 편안하게 즐길 수 있도록 친절한 안내를 제공합니다. 성남 분당 및 수정구 일대에서 접근성이 좋고, 주중에는 비교적 여유롭게 이용 가능합니다. 성남에서 합법적인 사교 댄스를 즐기고 싶은 분들에게 추천하는 업소입니다.',
    short_description: '성남 대표 나이트클럽. 소셜 댄스와 라이브 밴드를 즐기는 사교 공간.',
    features: ['소셜 댄스', '라이브 밴드', '파트너 매칭'],
    atmosphere: ['자유로운', '사교적', '편안한'],
    age_group: '30대~50대',
    dress_code: '',
    best_time: '',
    parking: '',
    nearby_station: '',
    image_url: '/images/venues/seongnam-shampoo-night.jpg',
    rating: 4.0,
    review_count: 0,
    is_premium: false,
    is_verified: true,
    status: 'verified_open',
    open_hours: '',
    tags: ['성남나이트', '샴푸나이트', '소셜댄스', '경기나이트'],
    staff_nickname: '박찬호',
    staff_phone: '010-3987-6885',
    district: '성남',
  },

  // ── 5. 수원찬스돔나이트 ──
  {
    slug: 'suwon-chance-dome-night',
    name: 'Suwon Chance Dome Night',
    name_ko: '수원찬스돔나이트',
    category: 'night',
    region: 'suwon',
    region_ko: '수원',
    address: '경기도 수원시 권선구 권선로 673',
    description: '수원찬스돔나이트는 경기도 수원시 권선구 권선로 673에 위치한 수원 최대 규모 나이트클럽입니다. 연중무휴 365일 운영하며, 20대부터 40대까지 폭넓은 연령층이 방문합니다. 대형 홀에 최신 사운드 시스템과 조명 시설을 갖추고 있으며, 라이브 밴드 공연과 DJ 세션이 번갈아 진행됩니다. 강호동 실장이 현장 운영을 책임지고 있으며, 부스석과 일반석을 선택하여 이용 가능합니다. 수원역에서 택시로 약 10분 거리에 있어 접근성이 좋고, 경기 남부 지역에서 나이트를 찾는 분들의 대표 선택지입니다.',
    short_description: '수원 최대 규모 나이트클럽. 365일 운영, 라이브 밴드와 DJ의 다채로운 무대.',
    features: ['대형 홀', '365일 운영', '라이브 밴드', 'DJ 세션', '부스석'],
    atmosphere: ['활기찬', '대형', '다양한 연령'],
    age_group: '20대~40대',
    dress_code: '',
    best_time: '',
    parking: '',
    nearby_station: '',
    image_url: '/images/venues/suwon-chance-dome-night.jpg',
    rating: 4.1,
    review_count: 0,
    is_premium: false,
    is_verified: true,
    status: 'verified_open',
    open_hours: '365일 운영',
    tags: ['수원나이트', '찬스돔', '수원', '경기나이트', '365일운영'],
    staff_nickname: '강호동',
    staff_phone: '010-9354-1323',
    district: '권선구',
  },

  // ── 6. 수유샴푸나이트 ──
  {
    slug: 'suyu-shampoo-night',
    name: 'Suyu Shampoo Night',
    name_ko: '수유샴푸나이트',
    category: 'night',
    region: 'seoul',
    region_ko: '서울',
    address: '',
    description: '수유샴푸나이트는 서울특별시 강북구 수유동에 위치한 나이트클럽입니다. 서울 강북 지역을 대표하는 소셜 댄스 공간으로, 수유역 인근의 편리한 접근성을 갖추고 있습니다. 샴푸나이트 특유의 자유로운 분위기에서 트로트와 팝송에 맞춰 소셜 댄스를 즐길 수 있으며, 강북 지역 주민과 직장인들이 퇴근 후 주로 방문합니다. 라이브 밴드가 상주하여 다양한 장르의 음악을 들려주며, 처음 오시는 분도 부담 없이 즐길 수 있는 편안한 분위기가 특징입니다. 서울 북부 지역에서 나이트를 찾는 분들의 꾸준한 선택지입니다.',
    short_description: '서울 수유동 소셜 댄스 나이트클럽. 강북 지역 대표 사교 공간.',
    features: ['소셜 댄스', '라이브 밴드', '편안한 분위기'],
    atmosphere: ['편안한', '자유로운', '사교적'],
    age_group: '30대~50대',
    dress_code: '',
    best_time: '',
    parking: '',
    nearby_station: '수유역',
    image_url: '/images/venues/suyu-shampoo-night.jpg',
    rating: 3.8,
    review_count: 0,
    is_premium: false,
    is_verified: false,
    status: 'unknown',
    open_hours: '',
    tags: ['수유나이트', '샴푸나이트', '강북나이트', '서울나이트'],
    staff_nickname: null,
    staff_phone: null,
    district: '수유동',
  },

  // ── 7. 신림그랑프리나이트 ──
  {
    slug: 'sinlim-grandprix-night',
    name: 'Sinlim Grandprix Night',
    name_ko: '신림그랑프리나이트',
    category: 'night',
    region: 'seoul',
    region_ko: '서울',
    address: '',
    description: '신림그랑프리나이트는 서울특별시 관악구 신림동에 위치한 나이트클럽으로, 서울 서남부 지역의 대표 나이트 업소입니다. 신림역 인근 유흥가에 자리 잡고 있어 대중교통 접근성이 뛰어나며, 넓은 댄스 홀과 다수의 좌석을 갖추고 있습니다. 태양 실장이 현장을 총괄하며, 라이브 밴드의 다채로운 음악에 맞춰 소셜 댄스를 즐길 수 있습니다. 주로 30대에서 50대 고객이 방문하며, 주말에는 자리가 빨리 차므로 사전 연락이 권장됩니다. 관악구와 금천구 일대에서 나이트를 즐기고 싶은 분들에게 오랫동안 인기를 끌어온 업소입니다.',
    short_description: '서울 신림동 대표 나이트클럽. 태양 실장 운영, 소셜 댄스와 라이브 밴드.',
    features: ['대형 댄스 홀', '라이브 밴드', '소셜 댄스'],
    atmosphere: ['활기찬', '사교적'],
    age_group: '30대~50대',
    dress_code: '',
    best_time: '',
    parking: '',
    nearby_station: '신림역',
    image_url: '/images/venues/sinlim-grandprix-night.jpg',
    rating: 4.0,
    review_count: 0,
    is_premium: false,
    is_verified: true,
    status: 'verified_open',
    open_hours: '',
    tags: ['신림나이트', '그랑프리', '관악나이트', '서울나이트', '소셜댄스'],
    staff_nickname: '태양',
    staff_phone: '010-4241-3748',
    district: '신림동',
  },

  // ── 8. 청담H2O나이트 ──
  {
    slug: 'cheongdam-h2o-night',
    name: 'Cheongdam H2O Night',
    name_ko: '청담H2O나이트',
    category: 'night',
    region: 'seoul',
    region_ko: '서울',
    address: '',
    description: '청담H2O나이트는 서울특별시 강남구 청담동에 위치한 프리미엄 나이트클럽으로, 100% 예약제로 운영되는 것이 가장 큰 특징입니다. 청담동 특유의 고급스러운 분위기와 세련된 인테리어를 갖추고 있으며, 서비스 수준이 높아 강남 지역 나이트 중에서도 프리미엄급으로 분류됩니다. 펩시맨 실장이 현장 운영을 담당하며, 사전 예약 시 VIP 부스와 일반 부스를 선택할 수 있습니다. 라이브 밴드와 DJ가 번갈아 무대에 올라 다양한 음악을 들려줍니다. 강남에서 격식 있는 나이트를 원하는 분들에게 최적의 선택지로, TripAdvisor에서도 활발한 리뷰가 확인되는 업소입니다.',
    short_description: '청담동 프리미엄 나이트클럽. 100% 예약제 운영, 고급스러운 분위기.',
    features: ['100% 예약제', 'VIP 부스', '라이브 밴드', 'DJ 세션', '프리미엄 인테리어'],
    atmosphere: ['고급', '세련된', '프리미엄'],
    age_group: '30대~50대',
    dress_code: '스마트 캐주얼 이상',
    best_time: '',
    parking: '',
    nearby_station: '',
    image_url: '/images/venues/cheongdam-h2o-night.jpg',
    rating: 4.4,
    review_count: 0,
    is_premium: true,
    is_verified: true,
    status: 'verified_open',
    open_hours: '',
    tags: ['청담나이트', 'H2O', '강남나이트', '프리미엄나이트', '예약제'],
    staff_nickname: '펩시맨',
    staff_phone: '010-5655-4866',
    district: '청담동',
  },

  // ── 9. 인덕원국빈관나이트 ──
  {
    slug: 'indeokwon-gukbingwan-night',
    name: 'Indeokwon Gukbingwan Night',
    name_ko: '인덕원국빈관나이트',
    category: 'night',
    region: 'indeokwon',
    region_ko: '인덕원',
    address: '',
    description: '인덕원국빈관나이트는 경기도 안양시 인덕원 지역에서 운영되었던 나이트클럽입니다. 인덕원역 인근에 위치하여 경기 서남부 지역 주민들이 즐겨 찾았던 사교 공간이었으나, 건물 철거로 인해 현재 영업 여부가 불확실한 상태입니다. 과거 넓은 홀과 라이브 밴드를 갖추고 소셜 댄스를 즐기는 3040 세대에게 인기가 높았습니다. 인덕원 지역 나이트 문화를 이끌었던 대표 업소 중 하나로, 현재 상태를 확인하시려면 직접 현장 방문 또는 전화 확인이 필요합니다. 과거 영업 당시에는 주변 직장인들의 회식 후 2차 장소로도 활용되었습니다.',
    short_description: '인덕원 지역 나이트클럽. 현재 영업 여부 확인 필요.',
    features: [],
    atmosphere: [],
    age_group: '30대~50대',
    dress_code: '',
    best_time: '',
    parking: '',
    nearby_station: '인덕원역',
    image_url: '/images/venues/indeokwon-gukbingwan-night.jpg',
    rating: 0,
    review_count: 0,
    is_premium: false,
    is_verified: false,
    status: 'closed_or_unclear',
    open_hours: '',
    tags: ['인덕원나이트', '국빈관', '안양나이트'],
    staff_nickname: null,
    staff_phone: null,
    district: '인덕원',
  },

  // ── 10. 파주야당스카이돔나이트 ──
  {
    slug: 'paju-yadang-skydome-night',
    name: 'Paju Yadang Skydome Night',
    name_ko: '파주야당스카이돔나이트',
    category: 'night',
    region: 'paju',
    region_ko: '파주',
    address: '',
    description: '파주야당스카이돔나이트는 경기도 파주시 야당역 인근에 위치한 나이트클럽으로, 파주 지역의 대표 사교 댄스 공간입니다. 스카이돔이라는 이름에 걸맞게 높은 천장과 개방적인 공간 설계가 특징이며, 넓은 댄스 플로어에서 라이브 밴드의 음악에 맞춰 소셜 댄스를 즐길 수 있습니다. 막내 실장이 현장 운영을 담당하고 있으며, 파주·일산·김포 등 경기 북부 지역 고객이 주로 방문합니다. 야당역에서 도보 접근이 가능하여 대중교통 이용에도 편리합니다. 경기 북부에서 나이트를 찾는 분들에게 접근성과 시설 면에서 추천할 만한 업소입니다.',
    short_description: '파주 야당역 인근 나이트클럽. 높은 천장의 개방적 공간, 소셜 댄스.',
    features: ['넓은 댄스 플로어', '높은 천장', '라이브 밴드'],
    atmosphere: ['개방적', '사교적'],
    age_group: '30대~50대',
    dress_code: '',
    best_time: '',
    parking: '',
    nearby_station: '야당역',
    image_url: '/images/venues/paju-yadang-skydome-night.jpg',
    rating: 3.9,
    review_count: 0,
    is_premium: false,
    is_verified: true,
    status: 'verified_open',
    open_hours: '',
    tags: ['파주나이트', '야당나이트', '스카이돔', '경기북부나이트'],
    staff_nickname: '막내',
    staff_phone: '010-8255-3509',
    district: '야당',
  },

  // ── 11. 울산챔피언나이트 ──
  {
    slug: 'ulsan-champion-night',
    name: 'Ulsan Champion Night',
    name_ko: '울산챔피언나이트',
    category: 'night',
    region: 'ulsan',
    region_ko: '울산',
    address: '',
    description: '울산챔피언나이트는 울산광역시에 위치한 나이트클럽으로, 울산 지역의 대표적인 사교 댄스 공간입니다. 넓은 홀과 고음질 사운드 시스템을 갖추고 있으며, 라이브 밴드가 트로트와 팝 음악을 연주하여 다양한 연령층이 함께 즐길 수 있습니다. 춘자 실장이 현장 운영을 총괄하며, 친절한 응대로 초보 방문객도 편안하게 이용할 수 있도록 돕고 있습니다. 울산 공단 지역 직장인들이 주말에 특히 많이 방문하며, 부스석과 스탠딩 모두 이용 가능합니다. 울산에서 나이트를 즐기려는 분들에게 오랜 기간 인기를 유지하고 있는 업소입니다.',
    short_description: '울산 대표 나이트클럽. 라이브 밴드와 소셜 댄스, 춘자 실장 운영.',
    features: ['대형 홀', '라이브 밴드', '부스석', '고음질 사운드'],
    atmosphere: ['활기찬', '사교적', '편안한'],
    age_group: '30대~50대',
    dress_code: '',
    best_time: '',
    parking: '',
    nearby_station: '',
    image_url: '/images/venues/ulsan-champion-night.jpg',
    rating: 4.0,
    review_count: 0,
    is_premium: false,
    is_verified: true,
    status: 'verified_open',
    open_hours: '',
    tags: ['울산나이트', '챔피언', '울산', '소셜댄스'],
    staff_nickname: '춘자',
    staff_phone: '010-5653-0069',
    district: '울산',
  },

  // ── 12. 일산샴푸나이트 ──
  {
    slug: 'ilsan-shampoo-night',
    name: 'Ilsan Shampoo Night',
    name_ko: '일산샴푸나이트',
    category: 'night',
    region: 'ilsan',
    region_ko: '일산',
    address: '',
    description: '일산샴푸나이트는 경기도 고양시 일산 지역에 위치한 나이트클럽으로, 일산 유흥가에서 소셜 댄스를 즐길 수 있는 공간입니다. 샴푸나이트 특유의 자유로운 파트너 매칭 분위기가 특징이며, 라이브 밴드가 트로트와 발라드 등 한국 대중가요를 중심으로 연주합니다. 일산 지역 직장인과 주민들이 퇴근 후나 주말에 주로 방문하며, 마두역 및 정발산역 인근에서 접근 가능합니다. 일산 지역에서 편안한 분위기의 나이트를 찾는 분들에게 꾸준히 사랑받고 있으며, 신규 방문객도 어렵지 않게 즐길 수 있는 자유로운 분위기가 강점입니다.',
    short_description: '일산 지역 소셜 댄스 나이트클럽. 자유로운 분위기의 사교 공간.',
    features: ['소셜 댄스', '라이브 밴드', '파트너 매칭'],
    atmosphere: ['자유로운', '편안한', '사교적'],
    age_group: '30대~50대',
    dress_code: '',
    best_time: '',
    parking: '',
    nearby_station: '',
    image_url: '/images/venues/ilsan-shampoo-night.jpg',
    rating: 3.7,
    review_count: 0,
    is_premium: false,
    is_verified: false,
    status: 'unknown',
    open_hours: '',
    tags: ['일산나이트', '샴푸나이트', '일산', '소셜댄스'],
    staff_nickname: null,
    staff_phone: null,
    district: '일산',
  },

  // ── 13. 인천아라비안나이트 ──
  {
    slug: 'incheon-arabian-night',
    name: 'Incheon Arabian Night',
    name_ko: '인천아라비안나이트',
    category: 'night',
    region: 'incheon',
    region_ko: '인천',
    address: '',
    description: '인천아라비안나이트는 인천광역시 계양구에 위치한 인천 최대 규모의 프리미엄 나이트클럽입니다. 아라비안나이트를 테마로 한 화려한 인테리어가 특징이며, 4개 층에 걸쳐 룸, VIP룸, 부스석 등 다양한 좌석 유형을 갖추고 있습니다. JBL과 Pioneer 전문 음향 시스템을 설치하여 높은 수준의 사운드 환경을 제공합니다. 인천 지역은 물론 경기 서부 지역 고객들까지 광범위한 고객층을 확보하고 있으며, TripAdvisor 리뷰에서도 활발한 평가가 확인됩니다. 인천에서 대형 나이트를 찾는 분들의 첫 번째 선택지입니다.',
    short_description: '인천 최대 규모 프리미엄 나이트클럽. 아라비안나이트 테마 인테리어, 4개 층.',
    features: ['4개 층 규모', 'VIP룸', 'JBL/Pioneer 사운드', '테마 인테리어', '부스석'],
    atmosphere: ['화려한', '대형', '프리미엄'],
    age_group: '30대~50대',
    dress_code: '',
    best_time: '',
    parking: '',
    nearby_station: '',
    image_url: '/images/venues/incheon-arabian-night.jpg',
    rating: 4.2,
    review_count: 0,
    is_premium: true,
    is_verified: true,
    status: 'verified_open',
    open_hours: '',
    tags: ['인천나이트', '아라비안', '인천', '프리미엄나이트', '대형나이트'],
    staff_nickname: null,
    staff_phone: null,
    district: '계양구',
  },

  // ── 14. 대전세븐나이트 ──
  {
    slug: 'daejeon-seven-night',
    name: 'Daejeon Seven Night',
    name_ko: '대전세븐나이트',
    category: 'night',
    region: 'daejeon',
    region_ko: '대전',
    address: '',
    description: '대전세븐나이트는 대전광역시에 위치한 나이트클럽으로, 대전 지역의 사교 댄스 문화를 이끌어온 업소입니다. 세련된 실내 인테리어와 넓은 댄스 플로어를 갖추고 있으며, 라이브 밴드가 다양한 장르의 음악을 연주하여 폭넓은 연령층이 즐길 수 있습니다. 대전 유성구 및 서구 일대에서 접근성이 좋으며, 공무원과 연구원 등 대전 특유의 직장인 고객층이 주로 방문합니다. 주말에는 특히 붐비므로 사전 방문 또는 연락이 권장됩니다. 대전 충청권에서 나이트를 찾는 분들에게 대표적인 선택지로 자리매김하고 있습니다.',
    short_description: '대전 대표 나이트클럽. 소셜 댄스와 라이브 밴드의 사교 공간.',
    features: ['넓은 댄스 플로어', '라이브 밴드', '세련된 인테리어'],
    atmosphere: ['세련된', '사교적'],
    age_group: '30대~50대',
    dress_code: '',
    best_time: '',
    parking: '',
    nearby_station: '',
    image_url: '/images/venues/daejeon-seven-night.jpg',
    rating: 3.8,
    review_count: 0,
    is_premium: false,
    is_verified: false,
    status: 'unknown',
    open_hours: '',
    tags: ['대전나이트', '세븐나이트', '대전', '충청나이트'],
    staff_nickname: null,
    staff_phone: null,
    district: '대전',
  },

  // ── 15. 상봉동한국관나이트 ──
  {
    slug: 'sangbong-hankukkwan-night',
    name: 'Sangbong Hankukkwan Night',
    name_ko: '상봉동한국관나이트',
    category: 'night',
    region: 'seoul',
    region_ko: '서울',
    address: '',
    description: '상봉동한국관나이트는 서울특별시 중랑구 상봉동에 위치한 나이트클럽으로, 서울 동북부 지역을 대표하는 사교 댄스 공간입니다. 한국관이라는 이름답게 전통적인 나이트클럽 분위기를 유지하며, 라이브 밴드의 트로트와 팝 음악에 맞춰 소셜 댄스를 즐길 수 있습니다. 상봉역 인근에 위치하여 대중교통 접근성이 좋고, 중랑구·노원구·광진구 일대 주민과 직장인이 주로 방문합니다. 주중에는 비교적 여유로운 분위기이며, 금요일과 토요일 저녁에 가장 활기찬 모습을 보입니다. 서울 동부에서 전통 나이트를 즐기고 싶은 분들에게 추천합니다.',
    short_description: '서울 상봉동 나이트클럽. 전통적 분위기의 소셜 댄스 공간.',
    features: ['소셜 댄스', '라이브 밴드', '전통 나이트 분위기'],
    atmosphere: ['전통적', '사교적', '편안한'],
    age_group: '30대~50대',
    dress_code: '',
    best_time: '',
    parking: '',
    nearby_station: '상봉역',
    image_url: '/images/venues/sangbong-hankukkwan-night.jpg',
    rating: 3.7,
    review_count: 0,
    is_premium: false,
    is_verified: false,
    status: 'unknown',
    open_hours: '',
    tags: ['상봉나이트', '한국관', '서울동부나이트', '소셜댄스'],
    staff_nickname: null,
    staff_phone: null,
    district: '상봉동',
  },

  // ── 16. 강남클럽레이스 (★클럽! 나이트 아님!) ──
  {
    slug: 'gangnam-club-race',
    name: 'Club RACE Gangnam',
    name_ko: '강남클럽레이스',
    category: 'club',
    region: 'gangnam',
    region_ko: '강남',
    address: '서울시 서초구 강남대로 597 지하 1층',
    description: '강남클럽레이스는 서울시 서초구 강남대로 597 지하 1층, 신사역 4번 출구 인근에 위치한 강남 대표 EDM 클럽입니다. 2022년 4월 오픈하여 강남 클럽 씬에서 빠르게 자리잡았으며, 대형 메인 플로어와 최신 음향·조명 시스템을 갖추고 있습니다. 국내외 유명 DJ가 정기적으로 게스트 공연을 펼치며, EDM·하우스·테크노 등 일렉트로닉 음악 중심으로 운영됩니다. 오후 11시부터 새벽까지 영업하며, 테이블 예약과 일반 입장 모두 가능합니다. 강남에서 클럽을 검색하면 상위에 노출되는 인지도 높은 업소로, 20대부터 30대 초반 고객이 주를 이룹니다.',
    short_description: '강남 대표 EDM 클럽. 신사역 인근, 대형 메인 플로어와 최신 사운드 시스템.',
    features: ['EDM 전문', '대형 플로어', '게스트 DJ', '테이블 예약 가능', '최신 사운드 시스템'],
    atmosphere: ['열정적', '트렌디', '대형'],
    age_group: '20대~30대 초반',
    dress_code: '스마트 캐주얼',
    best_time: '금토 23시 이후',
    parking: '',
    nearby_station: '신사역 4번 출구',
    image_url: '/images/venues/gangnam-club-race.jpg',
    rating: 4.3,
    review_count: 0,
    is_premium: false,
    is_verified: true,
    status: 'verified_open',
    open_hours: '23:00~11:00',
    tags: ['강남클럽', '클럽레이스', 'EDM', '강남', '신사역클럽'],
    staff_nickname: null,
    staff_phone: null,
    district: '서초구',
  },

  // ── 17. 강남클럽사운드 (★클럽!) ──
  {
    slug: 'gangnam-club-sound',
    name: 'Club SOUND Gangnam',
    name_ko: '강남클럽사운드',
    category: 'club',
    region: 'gangnam',
    region_ko: '강남',
    address: '서울 강남구 도산대로 114 지하',
    description: '강남클럽사운드는 서울 강남구 도산대로 114 지하, 신사역 1번 출구 인근에 위치한 EDM·힙합 클럽입니다. 클럽레이스와 같은 운영 그룹에 속해 있으며, EDM·힙합·트랩 등 다양한 장르의 음악을 섞어 플레이하는 것이 특징입니다. 오후 11시부터 오전 9시까지 영업하며, 넓은 메인 홀과 별도 VIP 공간을 갖추고 있습니다. 강남 클럽 랭킹에서 상위권을 꾸준히 유지하고 있으며, 주말에는 대기가 발생할 수 있어 테이블 사전 예약이 권장됩니다. 20대 중후반의 젊은 층이 주 고객이며, 신사역과 압구정 사이 접근성이 좋습니다.',
    short_description: '강남 EDM·힙합 클럽. 신사역 인근, 다양한 장르 믹스가 특징.',
    features: ['EDM/힙합/트랩', 'VIP 공간', '테이블 예약', '대형 메인 홀'],
    atmosphere: ['트렌디', '열정적', '다양한 장르'],
    age_group: '20대~30대',
    dress_code: '스마트 캐주얼',
    best_time: '금토 23시 이후',
    parking: '',
    nearby_station: '신사역 1번 출구',
    image_url: '/images/venues/gangnam-club-sound.jpg',
    rating: 4.2,
    review_count: 0,
    is_premium: false,
    is_verified: true,
    status: 'verified_open',
    open_hours: '23:00~09:00',
    tags: ['강남클럽', '클럽사운드', 'EDM', '힙합', '강남', '신사역'],
    staff_nickname: null,
    staff_phone: null,
    district: '강남구',
  },

  // ── 18. 이태원클럽와이키키유토피아 (★클럽!) ──
  {
    slug: 'itaewon-club-waikiki-utopia',
    name: 'Waikiki Utopia Itaewon',
    name_ko: '이태원클럽와이키키유토피아',
    category: 'club',
    region: 'itaewon',
    region_ko: '이태원',
    address: '서울 용산구 이태원로 173-7 B1',
    description: '이태원클럽와이키키유토피아는 서울 용산구 이태원로 173-7 지하 1층, 와이키키 본점 지하에 위치한 클럽입니다. 힙합·레게톤·아프로비츠 등 이태원 특유의 다양한 음악 장르가 특징이며, 금요일·토요일·일요일 밤 9시부터 새벽까지 영업합니다. 이태원 클럽 씬의 독특한 다문화적 분위기를 경험할 수 있으며, 외국인 방문객도 많아 글로벌한 파티 문화를 느낄 수 있습니다. 활발한 인스타그램 계정을 운영하고 있으며, 이태원에서 주말 밤을 보내려는 클러버들에게 인기 있는 업소입니다. 와이키키 본점에서 식사 후 지하 클럽으로 이동하는 코스가 일반적입니다.',
    short_description: '이태원 힙합·레게톤 클럽. 와이키키 본점 지하, 금토일 영업.',
    features: ['힙합/레게톤/아프로비츠', '다문화 분위기', '주말 영업 (금토일)'],
    atmosphere: ['글로벌', '자유로운', '다문화적'],
    age_group: '20대~30대',
    dress_code: '자유',
    best_time: '금토일 21시 이후',
    parking: '',
    nearby_station: '이태원역',
    image_url: '/images/venues/itaewon-club-waikiki-utopia.jpg',
    rating: 4.1,
    review_count: 0,
    is_premium: false,
    is_verified: true,
    status: 'verified_open',
    open_hours: '금토일 21:00~08:00',
    tags: ['이태원클럽', '와이키키', '유토피아', '힙합', '이태원'],
    staff_nickname: null,
    staff_phone: null,
    district: '이태원',
  },

  // ── 19. 강남라운지하입 ──
  {
    slug: 'gangnam-lounge-hype',
    name: 'Lounge HYPE Gangnam',
    name_ko: '강남라운지하입',
    category: 'lounge',
    region: 'gangnam',
    region_ko: '강남',
    address: '',
    description: '강남라운지하입은 서울 강남구 압구정동 일대에 위치한 것으로 알려진 라운지 업소입니다. 강남 압구정 지역의 라운지바 밀집 지역에 자리하고 있으며, 프라이빗한 분위기에서 음료와 대화를 즐길 수 있는 공간으로 소개되고 있습니다. 다만 현재 웹 검색을 통해 정확한 주소, 영업시간, 운영 현황에 대한 명확한 확인이 어려운 상태입니다. 방문 전 반드시 현장 확인 또는 전화를 통해 영업 여부를 확인하시기 바랍니다. 압구정 지역에는 다수의 라운지바가 밀집해 있어, 해당 업소가 이전되었거나 상호가 변경되었을 가능성도 있습니다.',
    short_description: '강남 압구정 지역 라운지. 영업 여부 확인 필요.',
    features: [],
    atmosphere: ['프라이빗'],
    age_group: '',
    dress_code: '',
    best_time: '',
    parking: '',
    nearby_station: '',
    image_url: '/images/venues/gangnam-lounge-hype.jpg',
    rating: 0,
    review_count: 0,
    is_premium: false,
    is_verified: false,
    status: 'unknown',
    open_hours: '',
    tags: ['강남라운지', '압구정라운지', '라운지하입'],
    staff_nickname: null,
    staff_phone: null,
    district: '압구정',
  },

  // ── 20. 강남라운지컬러 ──
  {
    slug: 'gangnam-lounge-color',
    name: 'Lounge COLOR Gangnam',
    name_ko: '강남라운지컬러',
    category: 'lounge',
    region: 'gangnam',
    region_ko: '강남',
    address: '',
    description: '강남라운지컬러는 서울 강남구 압구정동에 위치했던 라운지 업소입니다. 과거 압구정 지역 라운지바 중 하나로 운영되었으나, 현재 웹 검색 결과에서 영업 관련 정보가 확인되지 않아 폐업했을 가능성이 높습니다. 2025년 기준 강남 클럽 및 라운지 랭킹에도 이름이 올라있지 않으며, 인스타그램이나 리뷰 사이트에서도 최근 활동이 발견되지 않습니다. 이 업소를 방문하려는 분은 반드시 사전에 현장 확인을 하시기 바랍니다. 압구정 일대 라운지를 찾으신다면 현재 영업중인 다른 업소를 먼저 확인하시는 것을 권장합니다.',
    short_description: '강남 압구정 지역 라운지. 폐업 가능성 있음, 확인 필요.',
    features: [],
    atmosphere: [],
    age_group: '',
    dress_code: '',
    best_time: '',
    parking: '',
    nearby_station: '',
    image_url: '/images/venues/gangnam-lounge-color.jpg',
    rating: 0,
    review_count: 0,
    is_premium: false,
    is_verified: false,
    status: 'closed_or_unclear',
    open_hours: '',
    tags: ['강남라운지', '압구정라운지', '라운지컬러'],
    staff_nickname: null,
    staff_phone: null,
    district: '압구정',
  },

  // ── 21. 강남라운지아르쥬 ──
  {
    slug: 'gangnam-lounge-arzu',
    name: 'Lounge Arzu Gangnam',
    name_ko: '강남라운지아르쥬',
    category: 'lounge',
    region: 'gangnam',
    region_ko: '강남',
    address: '',
    description: '강남라운지아르쥬는 서울 강남구 압구정동 일대에 위치한 프리미엄 라운지입니다. 세련되고 고급스러운 인테리어가 특징이며, 프라이빗한 분위기에서 칵테일과 음료를 즐길 수 있는 공간으로 운영되고 있습니다. 압구정 로데오 인근의 라운지 밀집 지역에 자리하고 있어, 퇴근 후 모임이나 소규모 파티에 적합합니다. 고급 라운지답게 인테리어와 서비스에 세심한 신경을 쓰고 있으며, 칵테일 메뉴가 다양한 것이 강점입니다. 강남에서 조용하고 격식 있는 라운지를 찾는 분들에게 추천할 만한 업소입니다. 방문 전 전화로 자리 여부를 확인하는 것이 좋습니다.',
    short_description: '강남 압구정 프리미엄 라운지. 세련된 인테리어와 칵테일 바.',
    features: ['프리미엄 인테리어', '칵테일 바', '프라이빗 공간'],
    atmosphere: ['고급', '세련된', '프라이빗'],
    age_group: '30대~40대',
    dress_code: '스마트 캐주얼',
    best_time: '저녁 8시 이후',
    parking: '',
    nearby_station: '압구정역',
    image_url: '/images/venues/gangnam-lounge-arzu.jpg',
    rating: 4.3,
    review_count: 0,
    is_premium: true,
    is_verified: false,
    status: 'unknown',
    open_hours: '',
    tags: ['강남라운지', '압구정라운지', '아르쥬', '칵테일바', '프리미엄라운지'],
    staff_nickname: null,
    staff_phone: null,
    district: '압구정',
  },

  // ══════════════════════════════════════════════════════════════
  // ★ 웹 검색 확인된 추가 업소
  // ══════════════════════════════════════════════════════════════

  // ── 클럽: 홍대 ──
  {
    slug: 'hongdae-club-nb2',
    name: 'Club NB2',
    name_ko: '클럽NB2',
    category: 'club',
    region: 'hongdae',
    region_ko: '홍대',
    address: '',
    description: '클럽NB2(노이즈베이스먼트2)는 서울 마포구 홍대입구역 인근에 위치한 홍대 대표 힙합 클럽으로, 2000년 설립 이래 20년 이상 홍대 클럽 씬을 이끌어온 전설적인 업소입니다. 힙합과 R&B를 중심으로 운영되며, 국내 유명 래퍼와 DJ들이 정기적으로 무대에 오릅니다. 평일 오후 10시부터 새벽 6시까지, 주말에는 9시 30분부터 새벽 7시까지 영업합니다. 홍대 클럽 문화의 상징과도 같은 존재로, 홍대에서 힙합 클럽을 찾는다면 가장 먼저 떠오르는 이름입니다. 활발한 인스타그램 계정(@clubnb_official)을 운영 중입니다.',
    short_description: '홍대 대표 힙합 클럽. 2000년 설립, 20년 이상 운영된 전설적 업소.',
    features: ['힙합/R&B 전문', '20년 이상 역사', '유명 래퍼 공연', '대형 플로어'],
    atmosphere: ['열정적', '힙합', '전설적'],
    age_group: '20대~30대',
    dress_code: '자유',
    best_time: '금토 22시 이후',
    parking: '',
    nearby_station: '홍대입구역',
    image_url: '/images/venues/hongdae-club-nb2.jpg',
    rating: 4.3,
    review_count: 0,
    is_premium: false,
    is_verified: true,
    status: 'verified_open',
    open_hours: '평일 22:00~06:00, 주말 21:30~07:00',
    tags: ['홍대클럽', 'NB2', '힙합클럽', '홍대', '노이즈베이스먼트'],
    staff_nickname: null,
    staff_phone: null,
    district: '홍대',
  },

  {
    slug: 'hongdae-club-m2',
    name: 'Club M2',
    name_ko: '클럽M2',
    category: 'club',
    region: 'hongdae',
    region_ko: '홍대',
    address: '',
    description: '클럽M2는 서울 마포구 홍대입구역 인근에 위치한 홍대 최대 규모의 일렉트로니카 클럽으로, 2004년 5월 오픈 이래 약 1,000명 수용 가능한 대형 공간을 자랑합니다. EDM·하우스·테크노 등 전자음악 중심으로 운영되며, 해외 유명 DJ 게스트 공연이 정기적으로 열립니다. 넓은 메인 플로어와 별도 라운지 공간을 갖추고 있어 다양한 방식으로 즐길 수 있습니다. 홍대 EDM 클럽의 대명사로, 클럽 페스티벌과 연계 이벤트도 자주 개최합니다. 홍대에서 대규모 EDM 파티를 원하는 클러버라면 반드시 방문해볼 만한 업소입니다.',
    short_description: '홍대 최대 EDM 클럽. 1,000명 수용, 2004년 오픈 이래 홍대 클럽 씬 상징.',
    features: ['1,000명 수용', 'EDM/하우스/테크노', '해외 DJ 게스트', '대형 메인 플로어', '라운지 공간'],
    atmosphere: ['대형', '열정적', 'EDM'],
    age_group: '20대~30대',
    dress_code: '자유',
    best_time: '금토 22시 이후',
    parking: '',
    nearby_station: '홍대입구역',
    image_url: '/images/venues/hongdae-club-m2.jpg',
    rating: 4.2,
    review_count: 0,
    is_premium: false,
    is_verified: true,
    status: 'verified_open',
    open_hours: '',
    tags: ['홍대클럽', 'M2', 'EDM클럽', '홍대', '대형클럽'],
    staff_nickname: null,
    staff_phone: null,
    district: '홍대',
  },

  {
    slug: 'hongdae-club-razer',
    name: 'Club Razer',
    name_ko: '클럽레이저',
    category: 'club',
    region: 'hongdae',
    region_ko: '홍대',
    address: '',
    description: '클럽레이저는 서울 마포구 홍대 지역에 2022년 12월 오픈한 하이브리드 클럽으로, EDM과 힙합을 모두 즐길 수 있는 것이 특징입니다. 목요일부터 일요일까지 밤 10시 30분부터 새벽 6시까지 영업하며, 오픈 이후 빠르게 홍대 톱3 EDM 클럽 중 하나로 자리잡았습니다. 최신 음향과 조명 시스템을 갖추고 있으며, 국내외 DJ들의 게스트 공연이 정기적으로 열립니다. 홍대 클럽 씬에서 비교적 신생이지만, 높은 완성도의 사운드와 파티 기획력으로 빠르게 인지도를 확보했습니다. EDM과 힙합을 한 곳에서 즐기고 싶은 분들에게 추천합니다.',
    short_description: '홍대 하이브리드 클럽. 2022년 오픈, EDM+힙합 동시 가능.',
    features: ['EDM+힙합 하이브리드', '최신 사운드 시스템', '목~일 영업'],
    atmosphere: ['트렌디', '열정적', '하이브리드'],
    age_group: '20대~30대',
    dress_code: '자유',
    best_time: '금토 22:30 이후',
    parking: '',
    nearby_station: '홍대입구역',
    image_url: '/images/venues/hongdae-club-razer.jpg',
    rating: 4.1,
    review_count: 0,
    is_premium: false,
    is_verified: true,
    status: 'verified_open',
    open_hours: '목~일 22:30~06:00',
    tags: ['홍대클럽', '레이저', 'EDM', '힙합', '하이브리드클럽'],
    staff_nickname: null,
    staff_phone: null,
    district: '홍대',
  },

  // ── 클럽: 강남 추가 ──
  {
    slug: 'gangnam-club-face',
    name: 'Club FACE Gangnam',
    name_ko: '클럽페이스',
    category: 'club',
    region: 'gangnam',
    region_ko: '강남',
    address: '',
    description: '클럽페이스는 서울 강남구 신논현역 인근에 위치한 대형 EDM 클럽으로, 지하 1층과 2층에 걸쳐 두 개의 플로어를 운영합니다. 한 층은 EDM 존, 다른 층은 힙합 존으로 구성되어 취향에 따라 선택할 수 있는 것이 강점입니다. 365일 연중무휴 운영하며, 평일 테이블 예약 35만원부터, 주말은 50만원부터 가능합니다. 공식 웹사이트(clubface.co.kr)를 통해 사전 예약이 가능하며, 강남 클럽 랭킹 상위에 꾸준히 이름을 올리고 있습니다. 신논현역에서 도보 접근 가능하여 접근성이 뛰어나며, 강남에서 규모 있는 클럽을 찾는 20~30대에게 인기가 높습니다.',
    short_description: '강남 대형 EDM 클럽. 2개 플로어(EDM존+힙합존), 365일 운영.',
    features: ['2개 플로어', 'EDM존+힙합존', '365일 운영', '테이블 예약'],
    atmosphere: ['대형', '트렌디', '다양한 장르'],
    age_group: '20대~30대',
    dress_code: '스마트 캐주얼',
    best_time: '금토 23시 이후',
    parking: '',
    nearby_station: '신논현역',
    image_url: '/images/venues/gangnam-club-face.jpg',
    rating: 4.2,
    review_count: 0,
    is_premium: false,
    is_verified: true,
    status: 'verified_open',
    open_hours: '365일 운영',
    tags: ['강남클럽', '클럽페이스', 'EDM', '힙합', '신논현역'],
    staff_nickname: null,
    staff_phone: null,
    district: '강남구',
  },

  // ── 나이트: 강남 ──
  {
    slug: 'cheongdam-juliana-night',
    name: 'Juliana Night Cheongdam',
    name_ko: '줄리아나나이트',
    category: 'night',
    region: 'gangnam',
    region_ko: '강남',
    address: '서울특별시 강남구 청담동 리베라호텔 B1',
    description: '줄리아나나이트는 서울 강남구 청담동 리베라호텔 지하 1층에 위치한 강남 대표 나이트클럽입니다. 오랜 역사를 가진 성인 사교 나이트로, 저녁 7시 30분부터 새벽 4시 30분까지 영업합니다. 넓은 댄스 홀과 고급스러운 인테리어가 특징이며, 라이브 밴드의 다양한 음악에 맞춰 소셜 댄스를 즐길 수 있습니다. 청담동의 위치 특성상 고급스러운 분위기를 원하는 3040 세대가 주로 방문하며, 부스석과 테이블석 선택이 가능합니다. 강남 나이트의 대명사로 오랜 기간 명성을 유지하고 있는 업소입니다.',
    short_description: '청담동 리베라호텔 B1 프리미엄 나이트. 오랜 역사의 강남 대표 사교 나이트.',
    features: ['리베라호텔 지하', '라이브 밴드', '부스석', '고급 인테리어'],
    atmosphere: ['고급', '세련된', '사교적'],
    age_group: '30대~50대',
    dress_code: '스마트 캐주얼 이상',
    best_time: '금토 20시 이후',
    parking: '호텔 주차 가능',
    nearby_station: '청담역',
    image_url: '/images/venues/cheongdam-juliana-night.jpg',
    rating: 4.3,
    review_count: 0,
    is_premium: true,
    is_verified: true,
    status: 'verified_open',
    open_hours: '19:30~04:30',
    tags: ['청담나이트', '줄리아나', '강남나이트', '프리미엄나이트', '사교댄스'],
    staff_nickname: null,
    staff_phone: null,
    district: '청담동',
  },

  // ── 나이트: 부산 ──
  {
    slug: 'busan-dongrae-asiad-night',
    name: 'Asiad Night Busan',
    name_ko: '부산아시아드나이트',
    category: 'night',
    region: 'busan',
    region_ko: '부산',
    address: '부산 동래구 온천장로107번길 32 허심청 지하 1-2층',
    description: '부산아시아드나이트는 부산 동래구 온천장 허심청 지하 1~2층에 위치한 부산 최대 규모의 나이트클럽입니다. 온천장역 3번 출구에서 도보 5분 거리에 있으며, 30~40대 고객이 주를 이루는 부킹 나이트로 운영됩니다. 넓은 메인 홀과 다수의 부스석을 갖추고 있어 대규모 인원도 수용 가능하며, 라이브 밴드가 상주하여 다양한 음악을 들려줍니다. 부산에서 가장 오래되고 큰 규모의 나이트 중 하나로, 인스타그램에서도 활발한 활동이 확인됩니다. 부산 나이트를 대표하는 업소로서 지역 내 인지도가 매우 높습니다.',
    short_description: '부산 동래 온천장 최대 규모 나이트. 허심청 지하, 30~40대 부킹 나이트.',
    features: ['부산 최대 규모', '허심청 지하', '라이브 밴드', '부킹 시스템', '부스석'],
    atmosphere: ['대형', '활기찬', '사교적'],
    age_group: '30대~40대',
    dress_code: '',
    best_time: '',
    parking: '',
    nearby_station: '온천장역 3번 출구 도보 5분',
    image_url: '/images/venues/busan-dongrae-asiad-night.jpg',
    rating: 4.2,
    review_count: 0,
    is_premium: false,
    is_verified: true,
    status: 'verified_open',
    open_hours: '',
    tags: ['부산나이트', '아시아드', '동래나이트', '온천장', '부킹나이트'],
    staff_nickname: null,
    staff_phone: null,
    district: '동래구',
  },

  // ── 나이트: 대구 ──
  {
    slug: 'daegu-babamba-night',
    name: 'BaBamBa Night Daegu',
    name_ko: '대구바밤바나이트',
    category: 'night',
    region: 'daegu',
    region_ko: '대구',
    address: '대구 달서구 달구벌대로 1910 지하1층',
    description: '대구바밤바나이트는 대구 달서구 달구벌대로 1910 지하 1층에 위치한 대구 대표 나이트클럽입니다. 연중무휴로 운영하며, 인스타그램(@babamba_nightclub)에서 활발한 활동이 확인되는 현역 업소입니다. 넓은 댄스 홀과 부스석을 갖추고 있으며, 라이브 밴드의 트로트와 팝 음악에 맞춰 소셜 댄스를 즐길 수 있습니다. 대구 달서구 및 수성구 일대에서 접근성이 좋고, 30대부터 50대까지 폭넓은 연령층이 방문합니다. 대구에서 나이트를 찾는 분들에게 가장 먼저 추천되는 업소 중 하나입니다.',
    short_description: '대구 달서구 대표 나이트. 연중무휴 운영, 소셜 댄스와 라이브 밴드.',
    features: ['연중무휴', '라이브 밴드', '부스석', '넓은 댄스 홀'],
    atmosphere: ['활기찬', '사교적'],
    age_group: '30대~50대',
    dress_code: '',
    best_time: '',
    parking: '',
    nearby_station: '',
    image_url: '/images/venues/daegu-babamba-night.jpg',
    rating: 4.0,
    review_count: 0,
    is_premium: false,
    is_verified: true,
    status: 'verified_open',
    open_hours: '연중무휴',
    tags: ['대구나이트', '바밤바', '달서구나이트', '대구', '소셜댄스'],
    staff_nickname: null,
    staff_phone: null,
    district: '달서구',
  },

  // ── 나이트: 광주 ──
  {
    slug: 'gwangju-cheomdan-mul-night',
    name: 'Cheomdan Mul Night Gwangju',
    name_ko: '광주첨단물나이트',
    category: 'night',
    region: 'gwangju',
    region_ko: '광주',
    address: '광주 광산구 월계동 임방울대로800번길 52',
    description: '광주첨단물나이트는 광주광역시 광산구 월계동 임방울대로800번길 52에 위치한 광주 대표 나이트클럽입니다. 첨단 지구 내에 자리하여 접근성이 좋으며, 인스타그램(@mool_night)에서 활발한 활동이 확인됩니다. 넓은 홀과 최신 사운드 시스템을 갖추고 있으며, 라이브 밴드와 DJ가 번갈아 무대에 올라 다양한 음악을 제공합니다. 광주 지역 3040 세대가 주로 방문하는 사교 댄스 공간으로, 주말에는 특히 붐비므로 사전 방문이 권장됩니다. 광주에서 나이트를 찾는 분들에게 대표적인 선택지입니다.',
    short_description: '광주 첨단 지구 대표 나이트. 넓은 홀과 라이브 밴드, 3040 사교 공간.',
    features: ['넓은 홀', '라이브 밴드', 'DJ', '최신 사운드'],
    atmosphere: ['활기찬', '사교적'],
    age_group: '30대~40대',
    dress_code: '',
    best_time: '',
    parking: '',
    nearby_station: '',
    image_url: '/images/venues/gwangju-cheomdan-mul-night.jpg',
    rating: 4.0,
    review_count: 0,
    is_premium: false,
    is_verified: true,
    status: 'verified_open',
    open_hours: '',
    tags: ['광주나이트', '첨단물나이트', '광주', '소셜댄스'],
    staff_nickname: null,
    staff_phone: null,
    district: '광산구',
  },

  // ── 나이트: 의정부 ──
  {
    slug: 'uijeongbu-hankukkwan-night',
    name: 'Hankukkwan Night Uijeongbu',
    name_ko: '의정부한국관나이트',
    category: 'night',
    region: 'uijeongbu',
    region_ko: '의정부',
    address: '경기도 의정부시 의정부동 베스트프라자 2층',
    description: '의정부한국관나이트는 경기도 의정부시 의정부동 베스트프라자 2층에 위치한 의정부 대표 나이트클럽입니다. 인스타그램(@uijeongbu_koreanight)과 페이스북에서 활발한 활동이 확인되며, 경기 북부 지역의 대표적인 사교 댄스 공간으로 자리잡고 있습니다. 라이브 밴드가 트로트와 팝 음악을 연주하며, 넓은 홀에서 소셜 댄스를 즐길 수 있습니다. 의정부역에서 접근이 편리하고, 의정부·양주·동두천 등 경기 북부 지역 주민과 직장인이 주로 방문합니다. 경기 북부에서 전통 나이트를 즐기고 싶은 분들에게 추천합니다.',
    short_description: '의정부 대표 나이트. 베스트프라자 2층, 경기 북부 사교 댄스 공간.',
    features: ['라이브 밴드', '소셜 댄스', '넓은 홀'],
    atmosphere: ['사교적', '편안한'],
    age_group: '30대~50대',
    dress_code: '',
    best_time: '',
    parking: '',
    nearby_station: '의정부역',
    image_url: '/images/venues/uijeongbu-hankukkwan-night.jpg',
    rating: 3.8,
    review_count: 0,
    is_premium: false,
    is_verified: true,
    status: 'verified_open',
    open_hours: '',
    tags: ['의정부나이트', '한국관', '경기북부나이트', '의정부'],
    staff_nickname: null,
    staff_phone: null,
    district: '의정부동',
  },

  // ── 나이트: 평택 ──
  {
    slug: 'pyeongtaek-hobak-night',
    name: 'Hobak Night Pyeongtaek',
    name_ko: '평택호박나이트',
    category: 'night',
    region: 'pyeongtaek',
    region_ko: '평택',
    address: '',
    description: '평택호박나이트는 경기도 평택시에 위치한 나이트클럽으로, 2014년부터 10년 이상 운영되어온 경기 남부 지역의 대표 나이트 업소입니다. 30~40대 고객이 주를 이루며, 라이브 밴드의 음악에 맞춰 소셜 댄스를 즐길 수 있습니다. 인스타그램에서 2025년 게시물이 확인되어 현재까지 활발히 운영 중인 것으로 확인됩니다. 평택 시내 통복시장 인근에 위치하여 접근성이 좋으며, 평택·안성·오산 등 경기 남부 지역 주민들이 주로 방문합니다. 오랜 운영 기간만큼 안정적인 서비스와 단골 고객층을 확보하고 있습니다.',
    short_description: '평택 대표 나이트. 2014년부터 10년 이상 운영, 3040 소셜 댄스.',
    features: ['10년 이상 운영', '라이브 밴드', '소셜 댄스'],
    atmosphere: ['안정적', '사교적'],
    age_group: '30대~40대',
    dress_code: '',
    best_time: '',
    parking: '',
    nearby_station: '',
    image_url: '/images/venues/pyeongtaek-hobak-night.jpg',
    rating: 3.8,
    review_count: 0,
    is_premium: false,
    is_verified: true,
    status: 'verified_open',
    open_hours: '',
    tags: ['평택나이트', '호박나이트', '경기남부나이트', '평택'],
    staff_nickname: null,
    staff_phone: null,
    district: '평택',
  },

  // ── 나이트: 창원 ──
  {
    slug: 'changwon-rururalra-night',
    name: 'RuluRalra Night Changwon',
    name_ko: '창원룰루랄라나이트',
    category: 'night',
    region: 'changwon',
    region_ko: '창원',
    address: '경남 창원시 성산구 상남동 22-4 모아엔트몰',
    description: '창원룰루랄라나이트는 경남 창원시 성산구 상남동 모아엔트몰에 위치한 창원 대표 나이트클럽입니다. 월요일부터 토요일 및 공휴일에 영업하며, 인스타그램(@lulu__lala._.cw, @rulruralra_nightclub_)에서 활발한 활동이 확인됩니다. 넓은 홀과 부스석을 갖추고 있으며, 라이브 밴드의 다양한 음악에 맞춰 소셜 댄스를 즐길 수 있습니다. 창원 상남동 유흥가 중심에 위치하여 접근성이 뛰어나며, 경남 지역 3040 세대가 주로 방문합니다. 창원에서 나이트를 찾는다면 가장 먼저 추천되는 업소입니다.',
    short_description: '창원 상남동 대표 나이트. 월~토 영업, 경남 지역 3040 사교 공간.',
    features: ['월~토 영업', '라이브 밴드', '부스석', '넓은 홀'],
    atmosphere: ['활기찬', '사교적'],
    age_group: '30대~40대',
    dress_code: '',
    best_time: '',
    parking: '',
    nearby_station: '',
    image_url: '/images/venues/changwon-rururalra-night.jpg',
    rating: 4.0,
    review_count: 0,
    is_premium: false,
    is_verified: true,
    status: 'verified_open',
    open_hours: '월~토, 공휴일',
    tags: ['창원나이트', '룰루랄라', '상남동', '경남나이트', '창원'],
    staff_nickname: null,
    staff_phone: null,
    district: '상남동',
  },

  // ── 나이트: 전주 ──
  {
    slug: 'jeonju-byeolbam-night',
    name: 'Byeolbam Night Jeonju',
    name_ko: '전주별밤나이트',
    category: 'night',
    region: 'jeonju',
    region_ko: '전주',
    address: '전북 전주시 완산구 여울로 19 6층',
    description: '전주별밤나이트는 전북 전주시 완산구 여울로 19 6층에 위치한 전주 대표 나이트클럽으로, 2021년 12월 오픈하여 운영 중입니다. 인스타그램(@jeonjustar)에서 활발한 활동이 확인되며, 저녁 7시부터 새벽 4시까지 매일 영업합니다. 라이브 밴드와 DJ가 번갈아 무대에 올라 트로트부터 팝까지 다양한 음악을 제공하며, 넓은 홀에서 소셜 댄스를 즐길 수 있습니다. 전주 완산구 중심부에 위치하여 접근성이 좋고, 전북 지역 3040 세대가 주로 방문하는 사교 공간입니다.',
    short_description: '전주 완산구 대표 나이트. 2021년 오픈, 매일 19~04시 영업.',
    features: ['매일 영업', '라이브 밴드', 'DJ', '넓은 홀'],
    atmosphere: ['활기찬', '사교적'],
    age_group: '30대~40대',
    dress_code: '',
    best_time: '',
    parking: '',
    nearby_station: '',
    image_url: '/images/venues/jeonju-byeolbam-night.jpg',
    rating: 3.9,
    review_count: 0,
    is_premium: false,
    is_verified: true,
    status: 'verified_open',
    open_hours: '19:00~04:00',
    tags: ['전주나이트', '별밤', '전주', '전북나이트'],
    staff_nickname: null,
    staff_phone: null,
    district: '완산구',
  },

  // ── 나이트: 제주 ──
  {
    slug: 'jeju-empire-night',
    name: 'Empire Night Jeju',
    name_ko: '제주엠파이어나이트',
    category: 'night',
    region: 'jeju',
    region_ko: '제주',
    address: '제주시 연동 신대로16길 57 7-9층',
    description: '제주엠파이어나이트는 제주시 연동 신대로16길 57, 7~9층에 위치한 제주 대표 나이트클럽으로, 2024년 12월 24일 오픈한 신규 업소입니다. 8층 스테이지/나이트와 9층 나이트클럽으로 구성된 2개 층 규모이며, 저녁 8시부터 새벽 4시까지 연중무휴 운영합니다. 제주시 연동 중심 상업지구에 위치하여 접근성이 좋고, 최신 시설과 인테리어를 갖추고 있습니다. 당근마켓 등 지역 플랫폼에서도 업소 정보가 확인되며, 제주도에서 나이트를 즐기려는 분들에게 새로운 선택지로 주목받고 있습니다.',
    short_description: '제주 연동 나이트. 2024년 오픈, 7~9층 2개 층 규모, 연중무휴.',
    features: ['2개 층 규모', '최신 시설', '연중무휴', '스테이지+나이트클럽'],
    atmosphere: ['신규', '활기찬'],
    age_group: '',
    dress_code: '',
    best_time: '',
    parking: '',
    nearby_station: '',
    image_url: '/images/venues/jeju-empire-night.jpg',
    rating: 3.8,
    review_count: 0,
    is_premium: false,
    is_verified: true,
    status: 'verified_open',
    open_hours: '20:00~04:00 연중무휴',
    tags: ['제주나이트', '엠파이어', '연동', '제주'],
    staff_nickname: null,
    staff_phone: null,
    district: '연동',
  },

  // ── 클럽: 부산 ──
  {
    slug: 'busan-club-806',
    name: 'Club 806 Busan',
    name_ko: '부산클럽806',
    category: 'club',
    region: 'busan',
    region_ko: '부산',
    address: '',
    description: '부산클럽806은 부산 서면에 위치한 대형 EDM 클럽으로, 부산 클럽 씬을 대표하는 업소 중 하나입니다. 공식 웹사이트(club806busan.co.kr)를 운영하며, 최신 EDM과 하우스 음악을 중심으로 파티를 진행합니다. 서면 유흥가 중심에 위치하여 부산 지하철 서면역에서 접근이 용이하며, 넓은 메인 플로어와 VIP 공간을 갖추고 있습니다. 국내외 DJ 게스트 이벤트를 정기적으로 개최하고 있으며, 부산의 젊은 클러버들 사이에서 높은 인지도를 확보하고 있습니다. 부산에서 EDM 클럽을 찾는다면 방문해볼 만한 업소입니다.',
    short_description: '부산 서면 대표 EDM 클럽. 최신 사운드와 DJ 이벤트.',
    features: ['EDM 전문', '대형 플로어', 'VIP 공간', '게스트 DJ 이벤트'],
    atmosphere: ['열정적', '트렌디'],
    age_group: '20대~30대',
    dress_code: '',
    best_time: '금토 23시 이후',
    parking: '',
    nearby_station: '서면역',
    image_url: '/images/venues/busan-club-806.jpg',
    rating: 4.1,
    review_count: 0,
    is_premium: false,
    is_verified: true,
    status: 'verified_open',
    open_hours: '',
    tags: ['부산클럽', '806', '서면클럽', 'EDM', '부산'],
    staff_nickname: null,
    staff_phone: null,
    district: '서면',
  },

  // ── 호빠: 강남 ──
  {
    slug: 'gangnam-hoppa-again',
    name: 'Again Hoppa Gangnam',
    name_ko: '강남어게인호빠',
    category: 'hoppa',
    region: 'gangnam',
    region_ko: '강남',
    address: '',
    description: '강남어게인호빠는 서울 강남구에 위치한 강남 최대 규모의 호스트클럽으로, 공식 웹사이트(gangnamagain.com)를 통해 영업 정보가 확인됩니다. 소규모 프라이빗 룸부터 대형 파티 룸까지 다양한 크기의 공간을 갖추고 있어, 소수 모임부터 단체 파티까지 수용 가능합니다. 전문 호스트가 상주하며, 세련된 인테리어와 음향 시스템이 특징입니다. 강남 호빠 시장에서 가장 큰 규모를 자랑하며, 여성 고객 중심의 프리미엄 서비스를 제공합니다. 강남에서 호스트클럽을 찾는 분들에게 가장 인지도 높은 업소 중 하나입니다.',
    short_description: '강남 최대 규모 호스트클럽. 다양한 룸과 전문 호스트 서비스.',
    features: ['강남 최대 규모', '다양한 룸', '전문 호스트', '프리미엄 서비스'],
    atmosphere: ['세련된', '프리미엄'],
    age_group: '20대~40대 여성',
    dress_code: '',
    best_time: '',
    parking: '',
    nearby_station: '',
    image_url: '/images/venues/gangnam-hoppa-again.jpg',
    rating: 4.0,
    review_count: 0,
    is_premium: false,
    is_verified: true,
    status: 'verified_open',
    open_hours: '',
    tags: ['강남호빠', '어게인', '호스트클럽', '강남'],
    staff_nickname: null,
    staff_phone: null,
    district: '강남',
  },

];

// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
// SEED EXECUTION
// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

async function seed() {
  console.log(`\n🌱 Seeding ${venues.length} venues to Supabase...\n`);

  // Upsert in batches of 10
  const BATCH_SIZE = 10;
  let success = 0;
  let failed = 0;

  for (let i = 0; i < venues.length; i += BATCH_SIZE) {
    const batch = venues.slice(i, i + BATCH_SIZE).map((v) => ({
      slug: v.slug,
      name: v.name,
      name_ko: v.name_ko,
      category: v.category,
      region: v.region,
      region_ko: v.region_ko,
      address: v.address || '',
      description: v.description,
      short_description: v.short_description,
      features: v.features,
      atmosphere: v.atmosphere,
      age_group: v.age_group || null,
      dress_code: v.dress_code || null,
      best_time: v.best_time || null,
      parking: v.parking || null,
      nearby_station: v.nearby_station || null,
      image_url: v.image_url || null,
      rating: v.rating,
      review_count: v.review_count,
      is_premium: v.is_premium,
      is_verified: v.is_verified,
      status: v.status,
      open_hours: v.open_hours || null,
      tags: v.tags,
      staff_nickname: v.staff_nickname,
      staff_phone: v.staff_phone,
      district: v.district,
      is_active: true,
    }));

    const { error } = await supabase
      .from('venues')
      .upsert(batch, { onConflict: 'slug' });

    if (error) {
      console.error(`  ❌ Batch ${Math.floor(i / BATCH_SIZE) + 1} failed:`, error.message);
      failed += batch.length;
    } else {
      console.log(`  ✅ Batch ${Math.floor(i / BATCH_SIZE) + 1}: ${batch.length} venues upserted`);
      success += batch.length;
    }
  }

  console.log(`\n📊 Results: ${success} success, ${failed} failed, ${venues.length} total\n`);
}

seed().catch(console.error);
