// AUTO-GENERATED by scripts/gen-venues-counts.mjs — do not edit
// HomePage 위폴드 "지금 핫한 곳" 4카드 정적 임베드. venues.ts(341KB) 로드 전에 즉시 렌더 → LCP/TBT 단축.
// VenueCard가 사용하는 필드만 추출 (id/slug/nameKo/regionKo/region/category/rating).
export type VenueTop4 = {
  id: string;
  slug: string;
  nameKo: string;
  regionKo: string;
  region: string;
  category: string;
  rating: number;
};
export const VENUES_TOP4: VenueTop4[] = [
  {
    "id": "v-001",
    "slug": "ilsanroom",
    "nameKo": "일산룸",
    "regionKo": "일산",
    "region": "ilsan",
    "category": "room",
    "rating": 0
  },
  {
    "id": "v-002",
    "slug": "haeundaegoguryeo",
    "nameKo": "해운대고구려",
    "regionKo": "부산 해운대",
    "region": "busan-haeundae",
    "category": "room",
    "rating": 0
  },
  {
    "id": "v-003",
    "slug": "ilsanmyeongwolgwanyojeong",
    "nameKo": "일산명월관요정",
    "regionKo": "일산",
    "region": "ilsan",
    "category": "yojeong",
    "rating": 0
  },
  {
    "id": "v-004",
    "slug": "cheongdamh2onight",
    "nameKo": "청담H2O나이트",
    "regionKo": "청담",
    "region": "cheongdam",
    "category": "night",
    "rating": 0
  }
];
