// AUTO-GENERATED by scripts/gen-image-manifest.mjs — do not edit.
// public/venues/{slug}-1.{webp,jpg,png} 보유 slug 집합.
export const VENUE_IMAGE_SLUGS: ReadonlySet<string> = new Set([

]);

export const hasVenueImage = (slug: string): boolean => VENUE_IMAGE_SLUGS.has(slug);

// 시즌29 — 슬러그별 실제 보유 이미지 슬롯 (1~4). 누락 슬롯은 컴포넌트가 렌더 skip → 404 0건.
const VENUE_IMAGE_SLOTS = new Map<string, readonly number[]>([

]);

export function getVenueImageSlots(slug: string): readonly number[] {
  return VENUE_IMAGE_SLOTS.get(slug) ?? [];
}
