// AUTO-GENERATED by scripts/gen-venues-counts.mjs — do not edit
// venues 전체 데이터(341KB) 분리. 카운트 등 정적 숫자만 필요한 곳에서 이걸 import.
// 이 모듈은 import해도 chunk 가벼움 → / 페이지 LCP 영향 0.
export const VENUES_TOTAL_OPEN = 121;
export const VENUES_BY_CATEGORY: Record<string, number> = {
  "club": 36,
  "night": 61,
  "lounge": 3,
  "room": 2,
  "yojeong": 1,
  "hoppa": 18
};
