// AUTO-GENERATED by scripts/gen-venues-counts.mjs — do not edit
// HomePage 위폴드 "지금 핫한 곳" 4카드 정적 임베드. venues.ts(341KB) 로드 전에 즉시 렌더 → LCP/TBT 단축.
// VenueCard가 사용하는 필드만 추출 (id/slug/nameKo/regionKo/region/category/rating).
export type VenueTop4 = {
  id: string;
  slug: string;
  nameKo: string;
  regionKo: string;
  region: string;
  category: string;
  rating: number;
};
// basis: 'popularity' = 28일 실측 점수순 / 'recent' = 최신 등록순 폴백 (데이터 미축적)
export const VENUES_TOP4_BASIS = 'recent';
export const VENUES_TOP4: VenueTop4[] = [
  {
    "id": "v-142",
    "slug": "itaewonclub-cakeshop",
    "nameKo": "이태원클럽 케이크샵",
    "regionKo": "이태원",
    "region": "itaewon",
    "category": "club",
    "rating": 0
  },
  {
    "id": "v-141",
    "slug": "gangnamclub-octagon",
    "nameKo": "강남클럽 옥타곤",
    "regionKo": "강남",
    "region": "gangnam",
    "category": "club",
    "rating": 0
  },
  {
    "id": "v-140",
    "slug": "changwon-lululalala",
    "nameKo": "창원룰루랄라나이트",
    "regionKo": "창원",
    "region": "changwon",
    "category": "night",
    "rating": 0
  },
  {
    "id": "v-139",
    "slug": "itaewon-savage",
    "nameKo": "이태원클럽 세비지",
    "regionKo": "이태원",
    "region": "itaewon",
    "category": "club",
    "rating": 0
  }
];
